"""initial schema

Revision ID: dd0d6237bbc3
Revises: 
Create Date: 2026-08-18 21:08:59.246462
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0d6237bbc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('curriculum_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_levels_id'), ['id'], unique=False)

    op.create_table('curriculum_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('curriculum_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_tracks_id'), ['id'], unique=False)

    op.create_table('dsa_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('solution_notes', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Float(), nullable=False),
    sa.Column('solved_status', sa.Boolean(), nullable=False),
    sa.Column('revision_status', sa.String(length=20), nullable=False),
    sa.Column('last_attempted', sa.DateTime(), nullable=True),
    sa.Column('next_revision', sa.DateTime(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dsa_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dsa_topics_id'), ['id'], unique=False)

    op.create_table('revision_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('review_interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_schedules_id'), ['id'], unique=False)
        batch_op.create_index('ix_revision_schedules_next_review', ['next_review'], unique=False)

    op.create_table('user_xp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_this_session', sa.Integer(), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_xp_user_id')
    )
    with op.batch_alter_table('user_xp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_xp_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_xp_user_id'), ['user_id'], unique=False)

    op.create_table('curriculum_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['curriculum_levels.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['curriculum_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_id'), ['id'], unique=False)

    op.create_table('curriculum_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['curriculum_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_modules_id'), ['id'], unique=False)

    op.create_table('curriculum_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('fast_trackable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_topics_id'), ['id'], unique=False)

    op.create_table('curriculum_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('mastery_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('hours_estimated', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_lessons_id'), ['id'], unique=False)

    op.create_table('curriculum_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_unofficial', sa.String(length=10), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_resources_id'), ['id'], unique=False)

    op.create_table('lesson_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('solution_notes', sa.Text(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_exercises_id'), ['id'], unique=False)

    op.create_table('lesson_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('mastery_requirement', sa.Boolean(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_questions_id'), ['id'], unique=False)

    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('dsa_topic_id', sa.Integer(), nullable=True),
    sa.Column('progress_state', sa.String(length=20), nullable=False),
    sa.Column('mastery_status', sa.String(length=20), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('total_streak_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dsa_topic_id'], ['dsa_topics.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_progress_id'))

    op.drop_table('user_progress')
    with op.batch_alter_table('lesson_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_questions_id'))

    op.drop_table('lesson_questions')
    with op.batch_alter_table('lesson_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_exercises_id'))

    op.drop_table('lesson_exercises')
    with op.batch_alter_table('curriculum_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_resources_id'))

    op.drop_table('curriculum_resources')
    with op.batch_alter_table('curriculum_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_lessons_id'))

    op.drop_table('curriculum_lessons')
    with op.batch_alter_table('curriculum_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_topics_id'))

    op.drop_table('curriculum_topics')
    with op.batch_alter_table('curriculum_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_modules_id'))

    op.drop_table('curriculum_modules')
    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_id'))

    op.drop_table('curriculum_subjects')
    with op.batch_alter_table('user_xp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_xp_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_xp_id'))

    op.drop_table('user_xp')
    with op.batch_alter_table('revision_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_revision_schedules_next_review')
        batch_op.drop_index(batch_op.f('ix_revision_schedules_id'))

    op.drop_table('revision_schedules')
    with op.batch_alter_table('dsa_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dsa_topics_id'))

    op.drop_table('dsa_topics')
    with op.batch_alter_table('curriculum_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_tracks_id'))

    op.drop_table('curriculum_tracks')
    with op.batch_alter_table('curriculum_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_levels_id'))

    op.drop_table('curriculum_levels')
    # ### end Alembic commands ###
