"""Domain 1: Arrays through composition."""

from __future__ import annotations

from _d1_helpers import (
    DJ_ABS,
    DJ_AL_LL,
    DJ_ARR,
    DJ_CHARS,
    DJ_CLASS,
    DJ_CTOR,
    DJ_DESIGN,
    DJ_IFACE,
    DJ_IFACE_TYPE,
    DJ_INH,
    DJ_MORE,
    DJ_OBJ,
    DJ_OVERRIDE,
    DJ_PM,
    DJ_POLY,
    DJ_SB,
    DJ_STRINGS,
    DSA_ARRAYS,
    DSA_LIST,
    DSA_REFS,
    DSA_STRINGS,
    H_P3_ARRAYS,
    H_P3_LISTS,
    H_P3_STRINGS,
    H_P4_OOP,
    H_P5_OBJREF,
    H_P5_OOP,
    H_P5_OVER,
    H_P5_PRIMREF,
    H_P6_UI,
    H_P6_WITHIN,
    H_P9_IFACE,
    H_P9_INH,
    H_P9_POLY,
    H_P12_MULTI,
    HELSINKI_NOTE,
    ex,
    q,
    r,
)
from _d1_part1 import CONTENT, _add

_add(
    "java-arrays",
    hours=1.5,
    objective="Allocate, index, traverse, and modify Java arrays, including bounds, references, and simple complexity.",
    explanation=(
        "A Java array has a fixed length after creation. Indices are 0..length-1. `arr[i]` is O(1) access. "
        "The variable holds a reference; assignment copies the reference (aliasing). "
        "Multidimensional arrays are arrays of arrays. Out-of-bounds throws ArrayIndexOutOfBoundsException. "
        "Do not turn this into the DSA arrays module: min/max/reverse/rotate/prefix-sum here are language fluency. "
        + DSA_ARRAYS
        + " C++ analogue: T[] is closer to a fixed buffer than std::vector (vector ≈ ArrayList later)."
    ),
    mastery=[
        "Explain Java array length, indexing, and reference semantics.",
        "Implement traversal, modification, min/max, reverse, and a simple prefix sum.",
        "State the time of a full traversal (O(n)).",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-arrays-primary", "Helsinki Part 3 — Arrays", H_P3_ARRAYS, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Array exercises. " + DSA_ARRAYS),
        r("java-arrays-reference", "Creating arrays", DJ_ARR, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative fixed-length array tutorial."),
        r("java-arrays-practice", "Helsinki Part 12 — Multidimensional data", H_P12_MULTI, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " Matrices as arrays of arrays. Keep it to traversal, not graph algorithms."),
    ],
    questions=[
        q("java-arrays-q1",
          "int[] a = new int[3]; a[0] is:",
          ["undefined", "null", "0", "3"],
          "0",
          "Numeric element arrays are zero-initialized.",
          mastery=True),
        q("java-arrays-q2",
          "int[] a = {1,2,3}; int[] b = a; b[0] = 9; a[0] is:",
          ["1", "9", "0", "compile error"],
          "9",
          "a and b alias the same array object."),
        q("java-arrays-q3",
          "Accessing a[a.length] throws because:",
          ["length is private.", "valid indices stop at length-1.",
           "length is 0-based and the last index is length.", "Java arrays are 1-based."],
          "valid indices stop at length-1.",
          "This is the bounds mistake you must not carry into DSA."),
        q("java-arrays-q4",
          "Why isn't this topic the DSA arrays module?",
          ["Java cannot reverse an array.",
           "Language mechanics (allocation, indexing, aliases) vs algorithmic patterns (two pointers, kadane, etc.).",
           "Helsinki forbids min/max.",
           "Arrays are deprecated."],
          "Language mechanics (allocation, indexing, aliases) vs algorithmic patterns (two pointers, kadane, etc.).",
          "You need both, in this order."),
        q("java-arrays-q5",
          "int[][] g = new int[2][3]; number of ints:",
          ["5", "6", "2", "3"],
          "6",
          "2 rows × 3 cols. Jagged arrays can differ per row."),
        q("java-arrays-q6",
          "Time to scan all n elements once:",
          ["O(1)", "O(log n)", "O(n)", "O(n^2) always"],
          "O(n)",
          "Each index visit is O(1); n visits are O(n)."),
        q("java-arrays-q7",
          "new String[3] element default:",
          ["\"\"", "null", "0", "false"],
          "null",
          "Reference arrays start as null slots."),
        q("java-arrays-q8",
          "arr.length vs arr.length():",
          ["Both work on arrays.", "length is a field on arrays; length() is a String method.",
           "length() is required for int[].", "They are identical."],
          "length is a field on arrays; length() is a String method.",
          "A common compile error when switching types."),
    ],
    exercises=[
        ex("java-arrays-ex1", "Array fluency (not a DSA set)",
           "Implement methods on int[]: min, max, reverse in place, rotate right by k (k may exceed n), frequency of a target, "
           "prefixSum returning a new array, and print a 3×3 matrix in row-major order. "
           "State O-time of each in comments. Do not start NeetCode here. "
           + DSA_ARRAYS,
           difficulty="intermediate"),
    ],
)

_add(
    "java-strings",
    hours=1.25,
    objective="Use String immutability, content comparison, and common parsing/transform operations.",
    explanation=(
        "String objects are immutable: concatenation builds a new String. Compare content with equals, not == "
        "(== is reference identity; interned literals can make == accidentally 'work'). "
        "charAt, substring, toCharArray, split, and Character methods cover most interview string work. "
        + DSA_STRINGS
    ),
    mastery=[
        "Explain immutability and why equals beats == for content.",
        "Implement palindrome, frequency, and a parse/transform.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-strings-primary", "Helsinki Part 3 — Using strings", H_P3_STRINGS, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " String exercises. " + DSA_STRINGS),
        r("java-strings-reference", "Strings", DJ_STRINGS, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative String tutorial."),
        r("java-strings-deep", "Characters", DJ_CHARS, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "char vs code points when you process text one unit at a time."),
    ],
    questions=[
        q("java-strings-q1",
          "String a = \"hi\"; String b = new String(\"hi\"); a == b is typically:",
          ["true, because contents match.",
           "false, because == compares references; equals would be true.",
           "a compile error.",
           "true only if interned by the assignment operator."],
          "false, because == compares references; equals would be true.",
          "Literals in the pool can make == true for a = \"hi\"; b = \"hi\". Never rely on that.",
          mastery=True),
        q("java-strings-q2",
          "s.toUpperCase() leaves s:",
          ["Mutated in place.", "Unchanged; the method returns a new String.",
           "null.", "Cleared."],
          "Unchanged; the method returns a new String.",
          "Immutability."),
        q("java-strings-q3",
          "\"a\" + \"b\" + \"c\" in a tight loop is often slower than StringBuilder because:",
          ["+ is illegal.", "each + may allocate a new String.",
           "StringBuilder cannot append letters.", "The JVM forbids +."],
          "each + may allocate a new String.",
          "The compiler sometimes rewrites simple + ; loops still want StringBuilder."),
        q("java-strings-q4",
          "s.substring(0, 2) on \"abcd\":",
          ["\"ab\"", "\"abc\"", "\"cd\"", "\"abcd\""],
          "\"ab\"",
          "End index is exclusive."),
        q("java-strings-q5",
          "Empty string vs null:",
          ["They compare equal with ==.",
           "\"\".equals(s) is safe if s may be null; s.equals(\"\") NPEs when s is null.",
           "null has length 0.",
           "Both are primitives."],
          "\"\".equals(s) is safe if s may be null; s.equals(\"\") NPEs when s is null.",
          "Or Objects.equals. DSA inputs are often non-null but you should know the NPE."),
        q("java-strings-q6",
          "Why teach equals now, before collections?",
          ["HashMap uses content equality for String keys.",
           "equals is deprecated.",
           "== is enough for all interviews.",
           "Helsinki forbids equals."],
          "HashMap uses content equality for String keys.",
          "Wrong equality is a silent hashing bug."),
    ],
    exercises=[
        ex("java-strings-ex1", "Text analyzer",
           "Read a line (or hardcode a paragraph). Implement: isPalindrome (ignore case), char frequency map as a printed table, "
           "word count via split, and a transform that strips punctuation. Use equals for palindrome, never ==. "
           + DSA_STRINGS,
           difficulty="intermediate"),
    ],
)

_add(
    "java-stringbuilder",
    hours=0.75,
    objective="Build strings efficiently with StringBuilder and know when String is enough.",
    explanation=(
        "StringBuilder is a mutable sequence. append/insert/delete mutate the same object. "
        "It is not thread-safe (StringBuffer is the older synchronized cousin; you do not need it here). "
        "Use String for immutable values and APIs; StringBuilder for loops that assemble text."
    ),
    mastery=[
        "Rewrite a quadratic concatenation loop with StringBuilder.",
        "Explain mutability vs String.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-stringbuilder-primary", "String builders", DJ_SB, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative StringBuilder tutorial. Helsinki has no dedicated verified StringBuilder section mapped."),
        r("java-stringbuilder-practice", "Helsinki Part 3 — Using strings", H_P3_STRINGS, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " String exercises; when an exercise concatenates in a loop, redo it with StringBuilder locally."),
    ],
    questions=[
        q("java-stringbuilder-q1",
          "sb.append(\"x\") returns:",
          ["void always in modern Java.",
           "the same StringBuilder, so you can chain calls.",
           "a new StringBuilder each time.",
           "a String."],
          "the same StringBuilder, so you can chain calls.",
          "Chaining is convenience; mutation still happens on one object.",
          mastery=True),
        q("java-stringbuilder-q2",
          "toString() on StringBuilder:",
          ["Shares the internal buffer forever with the String (you can keep mutating the String).",
           "Produces a String snapshot; further sb.append does not change that String.",
           "Is illegal.",
           "Clears the builder."],
          "Produces a String snapshot; further sb.append does not change that String.",
          "String stays immutable."),
        q("java-stringbuilder-q3",
          "When is plain String concatenation fine?",
          ["Never.", "A few pieces, not inside a large loop.",
           "Only in JShell.", "Only for hex."],
          "A few pieces, not inside a large loop.",
          "Readability first for tiny cases."),
        q("java-stringbuilder-q4",
          "Passing StringBuilder into a method that appends:",
          ["Cannot affect the caller (pass-by-value of primitives only).",
           "Mutates the same builder the caller holds.",
           "Copies all characters automatically.",
           "Requires synchronized."],
          "Mutates the same builder the caller holds.",
          "Same reference-copy story as arrays."),
    ],
    exercises=[
        ex("java-stringbuilder-ex1", "Build vs + in a loop",
           "Time (even roughly, with System.nanoTime) building a 20_000-character string with += in a loop vs StringBuilder.append. "
           "Print both durations. Implement csvJoin(String[] parts) with StringBuilder. Do not claim microbenchmark scientific accuracy; explain the allocation difference."),
    ],
)

_add(
    "java-classes-objects",
    hours=1.25,
    objective="Define a class with state and behavior and construct objects with new.",
    explanation=(
        "A class is the blueprint; an object is an instance. Fields hold state; methods are behavior. "
        "`new` allocates and runs a constructor. `this` is the current instance. "
        "Access control starts here (public/private) and continues in encapsulation. "
        "Build small domain models (Student, Book), not CRUD apps. "
        + DSA_REFS.split("Java is")[0]
    ),
    mastery=[
        "Write a class with fields, methods, and object creation.",
        "Explain class vs object.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-classes-objects-primary", "Helsinki Part 4 — Introduction to OOP", H_P4_OOP, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " First classes and objects."),
        r("java-classes-objects-reference", "Creating classes", DJ_CLASS, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative class definition tutorial."),
        r("java-classes-objects-deep", "Creating and using objects", DJ_OBJ, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Object creation and use."),
    ],
    questions=[
        q("java-classes-objects-q1",
          "new Student() does what?",
          ["Declares a type alias.", "Allocates an object and runs a constructor.",
           "Deletes a class file.", "Prints the class."],
          "Allocates an object and runs a constructor.",
          "The expression yields a reference.",
          mastery=True),
        q("java-classes-objects-q2",
          "Two Student objects can have different name fields because:",
          ["Fields are static by default.", "Each instance has its own field storage.",
           "Java copies the class per call.", "Names must be unique globally."],
          "Each instance has its own field storage.",
          "static would share one copy."),
        q("java-classes-objects-q3",
          "this.name = name; in a constructor:",
          ["Renames the class.", "Assigns the parameter into the instance field, disambiguating names.",
           "Creates a subclass.", "Is required for all fields named x."],
          "Assigns the parameter into the instance field, disambiguating names.",
          "Without this, name = name is a no-op on the parameter."),
        q("java-classes-objects-q4",
          "A class with only static methods and no instances is:",
          ["Invalid Java.", "Sometimes used for utilities; it is not OOP modeling.",
           "The only style Helsinki allows.", "Required for DSA trees."],
          "Sometimes used for utilities; it is not OOP modeling.",
          "Domain objects use instance state."),
        q("java-classes-objects-q5",
          "Why a BankAccount object instead of three parallel arrays of ids/balances/names?",
          ["Arrays cannot store ints.",
           "The object's invariants and operations stay together; DSA later still uses arrays when that is the point.",
           "Objects are always faster.",
           "Java forbids arrays after this topic."],
          "The object's invariants and operations stay together; DSA later still uses arrays when that is the point.",
          "Choose the model that matches the problem."),
    ],
    exercises=[
        ex("java-classes-objects-ex1", "Two domain objects",
           "Implement Book (title, author, pages) and Student (id, name) with methods that print a one-line summary. "
           "Construct at least two of each in main. Do not build a database or REST API. "
           "Optional third: Product with price in cents (int) and a method to apply a percent discount without using float money if you can avoid it.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-references",
    hours=1.5,
    objective="Explain Java references, aliasing, null, and pass-by-value of references; predict mutation.",
    explanation=(
        "A reference variable holds either null or an identity of an object. Assignment `a = b` copies the reference. "
        "Mutating through either name changes the one object. Rebinding `a = new ...` does not change b. "
        "This is the mental model for linked lists, trees, and graphs. Java is not pass-by-reference. "
        + DSA_REFS
    ),
    mastery=[
        "Explain pass-by-value of references without calling Java pass-by-reference.",
        "Demonstrate aliasing (`a = b`) and mutation.",
        "Predict which object changes in a short snippet.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-references-primary", "Helsinki Part 5 — Objects and references", H_P5_OBJREF, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Aliasing and object references. " + DSA_REFS),
        r("java-references-reference", "Helsinki Part 5 — Primitive and reference variables", H_P5_PRIMREF, "University of Helsinki",
          "REFERENCE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Primitive vs reference variables."),
        r("java-references-deep", "Creating and using objects", DJ_OBJ, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Object use; combine with the aliasing lesson. Dev.java does not replace the pass-by-value explanation."),
    ],
    questions=[
        q("java-references-q1",
          "Node a = new Node(1); Node b = a; b.value = 2; a.value is:",
          ["1", "2", "null", "undefined"],
          "2",
          "One node, two names.",
          mastery=True),
        q("java-references-q2",
          "After b = new Node(3); a.value is:",
          ["Still 2 from the previous question's object (a was not rebound).",
           "3",
           "Always 1",
           "0"],
          "Still 2 from the previous question's object (a was not rebound).",
          "Rebinding b does not rebind a."),
        q("java-references-q3",
          "Calling a method void link(Node n) { n.next = n; } with the caller's head:",
          ["Cannot change the caller's object.",
           "Can mutate the node the copied reference points to (e.g. set next).",
           "Always clones the list.",
           "Is pass-by-reference of the variable head."],
          "Can mutate the node the copied reference points to (e.g. set next).",
          "If the method does n = null, the caller's head is unchanged."),
        q("java-references-q4",
          "null means:",
          ["The empty string.", "The reference does not point at an object; dereferencing throws NPE.",
           "0 for all types.", "A special Node."],
          "The reference does not point at an object; dereferencing throws NPE.",
          "List ends and missing children are often null."),
        q("java-references-q5",
          "Why is 'Java is pass-by-reference' wrong?",
          ["Because objects live on the stack only.",
           "Because the thing copied is the reference value, not a live binding to the caller's variable.",
           "Because Java has no objects.",
           "Because C++ is pass-by-value only."],
          "Because the thing copied is the reference value, not a live binding to the caller's variable.",
          "C++ can pass T&; Java cannot rebind the caller's variable."),
        q("java-references-q6",
          "An object graph is:",
          ["A GUI library.", "Objects pointing at other objects via fields (next, left/right, neighbors).",
           "Only HashMap.", "Bytecode."],
          "Objects pointing at other objects via fields (next, left/right, neighbors).",
          "DSA structures are object graphs."),
        q("java-references-q7",
          "Identity vs equality: two Node objects with value 1:",
          ["== is always true.", "== is true only if they are the same instance; equals may be defined separately.",
           "equals cannot be defined.", "They cannot both exist."],
          "== is true only if they are the same instance; equals may be defined separately.",
          "Lists usually care about identity of nodes, maps about key equals/hashCode."),
        q("java-references-q8",
          "Stack vs heap at programmer level:",
          ["References in method frames point at objects (typically on the heap).",
           "All objects live in CPU registers only.",
           "null is stored in the instruction cache.",
           "Java has no stack."],
          "References in method frames point at objects (typically on the heap).",
          "Enough for DSA; JVM internals come later."),
    ],
    exercises=[
        ex("java-references-ex1", "Aliasing lab",
           "Create a tiny Box { int x; } or use a one-field class. "
           "1) a = new; b = a; mutate via b; print a. "
           "2) method mutate(Box b) { b.x++; } "
           "3) method rebind(Box b) { b = new Box(); b.x = 99; } show the caller is unchanged. "
           "4) Draw (comments/ASCII) a two-node linked list and set node.next. "
           "Write: 'Java is pass-by-value' in your own words. "
           + DSA_REFS,
           difficulty="intermediate"),
    ],
)

_add(
    "java-constructors",
    hours=0.75,
    objective="Write constructors, overload them, and chain with this(...).",
    explanation=(
        "Constructors initialize new objects. They have no return type. You can overload them. "
        "`this(...)` must be the first statement when chaining. If you write any constructor, Java does not supply the default no-arg one."
    ),
    mastery=[
        "Write at least two overloaded constructors.",
        "Explain default constructor rules.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-constructors-primary", "Providing constructors", DJ_CTOR, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative constructors tutorial."),
        r("java-constructors-practice", "Helsinki Part 5 — Method and constructor overloading", H_P5_OVER, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Constructor overloading exercises."),
    ],
    questions=[
        q("java-constructors-q1",
          "If you write Student(String name) only, new Student() :",
          ["Calls a generated no-arg constructor.", "Does not compile (no no-arg constructor).",
           "Sets name to \"\".", "Throws at runtime."],
          "Does not compile (no no-arg constructor).",
          "The default constructor exists only if you write none.",
          mastery=True),
        q("java-constructors-q2",
          "this(0, \"x\") in another constructor:",
          ["Must be first; it reuses initialization logic.",
           "Can appear after field assignments.",
           "Creates a subclass.",
           "Is the same as super()."],
          "Must be first; it reuses initialization logic.",
          "super() is for inheritance."),
        q("java-constructors-q3",
          "A constructor that only assigns fields is:",
          ["Illegal; use setters only.", "Normal; keep it simple and enforce invariants.",
           "Required to be public.", "Required to throw."],
          "Normal; keep it simple and enforce invariants.",
          "Reject illegal values (negative prices) in the constructor."),
        q("java-constructors-q4",
          "Return type on a constructor:",
          ["void", "the class name as a type", "none — if you write void, it becomes a method", "Object"],
          "none — if you write void, it becomes a method",
          "A common bug: void Student() looks like a constructor but is not."),
    ],
    exercises=[
        ex("java-constructors-ex1", "Employee constructors",
           "Employee with id, name, salaryCents. Provide (id, name, salary), (id, name) defaulting salary to 0, "
           "and reject negative salary. Chain constructors with this(...). Try new Employee() and record the compile error if you omitted no-arg."),
    ],
)

_add(
    "java-encapsulation",
    hours=1.0,
    objective="Hide representation, protect invariants, and use accessors only when they earn their keep.",
    explanation=(
        "Encapsulation: keep fields private and expose a small API that preserves invariants (balance >= 0). "
        "Getters/setters are not mandatory boilerplate. A public setter that allows any value destroys the invariant. "
        "Prefer immutable fields when mutation is not part of the domain."
    ),
    mastery=[
        "Design a domain object with at least one invariant.",
        "Explain when a setter is harmful.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-encapsulation-primary", "Helsinki Part 5 — Learning OOP", H_P5_OOP, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Encapsulation and object APIs."),
        r("java-encapsulation-reference", "More on classes (this, access control)", DJ_MORE, "Dev.java",
          "REFERENCE", "documentation", 1,
          "this and access control."),
    ],
    questions=[
        q("java-encapsulation-q1",
          "A public int balance field is risky because:",
          ["ints cannot be public.", "callers can violate invariants without going through methods.",
           "the JVM ignores public.", "private is slower."],
          "callers can violate invariants without going through methods.",
          "withdraw() can check funds; a field write cannot.",
          mastery=True),
        q("java-encapsulation-q2",
          "Getters/setters for every field:",
          ["Are required by Java.",
           "Can be pointless or harmful if they expose a mutable representation with no rules.",
           "Replace constructors.",
           "Are forbidden in interviews."],
          "Can be pointless or harmful if they expose a mutable representation with no rules.",
          "Expose behavior (deposit), not a bag of fields."),
        q("java-encapsulation-q3",
          "Returning the internal List field from getItems():",
          ["Always fine.", "Lets callers mutate internals unless you copy or return an unmodifiable view.",
           "Makes the list private automatically.", "Is required for DSA."],
          "Lets callers mutate internals unless you copy or return an unmodifiable view.",
          "Encapsulation is about representation hiding."),
        q("java-encapsulation-q4",
          "Cohesion means:",
          ["One class does networking, parsing, and UI.", "A class's methods belong to one responsibility.",
           "All fields are public.", "Using inheritance always."],
          "A class's methods belong to one responsibility.",
          "Split UI from domain (Helsinki also separates UI from logic)."),
        q("java-encapsulation-q5",
          "private vs package vs public:",
          ["Only public exists in Java.",
           "private is class-only; default is package; public is API.",
           "private methods cannot call each other.",
           "public fields are required for main."],
          "private is class-only; default is package; public is API.",
          "protected waits for inheritance."),
    ],
    exercises=[
        ex("java-encapsulation-ex1", "Invariant BankAccount",
           "Private balanceCents. deposit/withdraw throw or return false on invalid amounts (your choice, be consistent). "
           "No public setter for balance. Write a main that tries to break the invariant and cannot. "
           "In comments: would a getter for balance be OK? (yes, read-only) Why no setter?",
           difficulty="intermediate"),
    ],
)

_add(
    "java-inheritance",
    hours=1.25,
    objective="Extend a class with super/override and judge when composition is the better is-a vs has-a choice.",
    explanation=(
        "extends creates an is-a relationship. Subclasses inherit accessible members, override methods, and chain constructors with super(). "
        "protected is for subclass access. Inheritance is not the default design tool: a fragile hierarchy is worse than composition. "
        "After the exercise, answer: would composition be better?"
    ),
    mastery=[
        "Implement a small hierarchy with super and override.",
        "Explain is-a vs has-a and a limitation of inheritance.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-inheritance-primary", "Helsinki Part 9 — Inheritance", H_P9_INH, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Inheritance exercises."),
        r("java-inheritance-reference", "What is inheritance?", DJ_INH, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative inheritance intro."),
        r("java-inheritance-deep", "Overriding", DJ_OVERRIDE, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Method overriding rules."),
    ],
    questions=[
        q("java-inheritance-q1",
          "super(name) in a subclass constructor:",
          ["Is optional if the superclass has only a parameterized constructor.",
           "Calls the superclass constructor; required when there is no no-arg super constructor.",
           "Overrides a method.",
           "Creates a copy of the subclass."],
          "Calls the superclass constructor; required when there is no no-arg super constructor.",
          "Java inserts super() only when a no-arg super constructor exists.",
          mastery=True),
        q("java-inheritance-q2",
          "A limitation of inheritance:",
          ["You cannot reuse any code.",
           "You get a tightly coupled hierarchy; reused code in the wrong parent infects all children.",
           "Overriding is illegal.",
           "super is deprecated."],
          "You get a tightly coupled hierarchy; reused code in the wrong parent infects all children.",
          "Composition plugs in a helper object instead."),
        q("java-inheritance-q3",
          "Stack extends ArrayList is a famous smell because:",
          ["ArrayList is final.",
           "Stack is-not-really-a List; clients can use ArrayList methods that break stack discipline.",
           "Java forbids extending collections.",
           "Stacks must be arrays."],
          "Stack is-not-really-a List; clients can use ArrayList methods that break stack discipline.",
          "Has-a List (composition) keeps the API small."),
        q("java-inheritance-q4",
          "@Override is useful because:",
          ["It makes methods static.",
           "The compiler checks you actually overrode a superclass method (typos become errors).",
           "It is required for private methods.",
           "It disables polymorphism."],
          "The compiler checks you actually overrode a superclass method (typos become errors).",
          "Use it."),
        q("java-inheritance-q5",
          "protected vs private:",
          ["protected members are visible to subclasses (and the package); private are not.",
           "private is visible to subclasses.",
           "protected means public.",
           "They are identical."],
          "protected members are visible to subclasses (and the package); private are not.",
          "Prefer private until a subclass genuinely needs it."),
    ],
    exercises=[
        ex("java-inheritance-ex1", "Hierarchy, then composition question",
           "Create Vehicle { id } and Car extends Vehicle { int doors } with an overridden description(). "
           "Then write a 6–8 sentence answer: for a ParkingLot that stores vehicles, is inheritance the right tool, "
           "or would ParkingLot compose a List<Vehicle>? Could Car instead compose an Engine? Pick one place where composition is better and say why.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-polymorphism",
    hours=1.25,
    objective="Call overridden methods through a supertype and explain compile-time types vs runtime dispatch.",
    explanation=(
        "The compile-time type of a variable decides which members you can name. The runtime class of the object decides which override runs "
        "(dynamic dispatch). Interface types work the same way. instanceof (and pattern matching) tests runtime type — use sparingly vs real polymorphism. "
        "Not a DSA gate, but it shows up in Java design."
    ),
    mastery=[
        "Write code whose behavior changes with runtime type.",
        "Explain static type vs dynamic dispatch.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-polymorphism-primary", "Helsinki Part 9 — Object polymorphism", H_P9_POLY, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Polymorphism exercises."),
        r("java-polymorphism-reference", "Polymorphism", DJ_POLY, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative polymorphism tutorial."),
        r("java-polymorphism-deep", "Pattern matching", DJ_PM, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Modern instanceof/pattern matching. Optional; not a DSA prerequisite."),
    ],
    questions=[
        q("java-polymorphism-q1",
          "Animal a = new Dog(); a.speak(); if Dog overrides speak:",
          ["Animal.speak always runs.", "Dog.speak runs (dynamic dispatch).",
           "Does not compile.", "Both run."],
          "Dog.speak runs (dynamic dispatch).",
          "Runtime type is Dog.",
          mastery=True),
        q("java-polymorphism-q2",
          "a.wag() when wag exists only on Dog:",
          ["Compiles because runtime is Dog.",
           "Does not compile; compile-time type Animal has no wag.",
           "Throws always.",
           "Is a static method."],
          "Does not compile; compile-time type Animal has no wag.",
          "Cast or give Animal a method. Prefer a method on the type you hold."),
        q("java-polymorphism-q3",
          "Overloading vs overriding:",
          ["They are the same.",
           "Overloading is compile-time by signature; overriding is runtime by class.",
           "Overriding is compile-time only.",
           "Overloading requires inheritance."],
          "Overloading is compile-time by signature; overriding is runtime by class.",
          "Do not mix the words in interviews."),
        q("java-polymorphism-q4",
          "A chain of instanceof checks instead of overrides is often:",
          ["The most extensible design.",
           "A sign you should put the behavior on the type (or a visitor) instead of switching on class.",
           "Required by the JVM.",
           "Faster than dispatch always."],
          "A sign you should put the behavior on the type (or a visitor) instead of switching on class.",
          "Pattern matching makes instanceof nicer; it does not fix a type-switch design by itself."),
        q("java-polymorphism-q5",
          "List<Animal> can hold Dog and Cat because:",
          ["Generics erase Animal.", "Dog and Cat are Animals; the list's static type is Animal.",
           "Lists ignore types.", "It is illegal."],
          "Dog and Cat are Animals; the list's static type is Animal.",
          "Getting an element yields Animal statically."),
    ],
    exercises=[
        ex("java-polymorphism-ex1", "Runtime behavior",
           "Shape with area(); Circle and Rectangle override it. Put mixed shapes in a Shape[] and print areas in one loop with no instanceof. "
           "Then write a bad version that instanceof-switches and comment why the override version is the point of this topic.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-abstract-classes",
    hours=0.75,
    objective="Declare abstract classes/methods and know when an interface is the better abstraction.",
    explanation=(
        "An abstract class cannot be instantiated. Abstract methods force subclasses to implement. "
        "Use an abstract class when you have shared fields/implementation plus holes to fill. "
        "Prefer interfaces for capability types (Payable, Comparable) — next topic."
    ),
    mastery=[
        "Write an abstract class with one abstract and one concrete method.",
        "Explain why you cannot new the abstract type.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-abstract-classes-primary", "Abstract classes", DJ_ABS, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative abstract class tutorial. Helsinki covers inheritance more broadly in Part 9."),
        r("java-abstract-classes-practice", "Helsinki Part 9 — Inheritance", H_P9_INH, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Inheritance material; implement the abstract-class exercise locally if Helsinki's page is thin on the keyword."),
    ],
    questions=[
        q("java-abstract-classes-q1",
          "new AbstractShape() when AbstractShape is abstract:",
          ["Creates a dummy instance.", "Does not compile.",
           "Creates a subclass automatically.", "Runs GC."],
          "Does not compile.",
          "You new a concrete subclass.",
          mastery=True),
        q("java-abstract-classes-q2",
          "An abstract method has:",
          ["A body that must be empty braces.", "No body; subclasses implement it.",
           "Must be static.", "Must be private."],
          "No body; subclasses implement it.",
          "private abstract is illegal."),
        q("java-abstract-classes-q3",
          "Abstract class vs interface (simple rule):",
          ["Always prefer abstract class.",
           "Shared state/implementation → abstract class is a candidate; multiple capabilities → interfaces.",
           "Interfaces cannot have methods.",
           "Abstract classes cannot have fields."],
          "Shared state/implementation → abstract class is a candidate; multiple capabilities → interfaces.",
          "Java allows default methods on interfaces too — still don't force a parent class."),
        q("java-abstract-classes-q4",
          "A concrete subclass must:",
          ["Implement all inherited abstract methods (or be abstract itself).",
           "Implement only private methods.",
           "Remove super fields.",
           "Be named Abstract..."],
          "Implement all inherited abstract methods (or be abstract itself).",
          "The compiler enforces this."),
    ],
    exercises=[
        ex("java-abstract-classes-ex1", "Employee hierarchy",
           "abstract Employee { String name; abstract int payCents(); String label() { return name; } } "
           "Salaried and Hourly subclasses. Put them in an Employee[] and print pay. Do not instantiate Employee."),
    ],
)

_add(
    "java-interfaces",
    hours=1.25,
    objective="Define and implement interfaces, including default/static methods, for backend-style substitutions.",
    explanation=(
        "An interface is a contract. A class implements it. Variables can have the interface type (dependency inversion intro: depend on PaymentProcessor, not StripeProcessor). "
        "Default methods add library evolution; static methods are helpers on the interface. Multiple interfaces are allowed; multiple class inheritance is not. "
        "Connects to later backend: storage, notifications, payment."
    ),
    mastery=[
        "Implement an interface in two classes and call through the interface type.",
        "Explain why the caller should depend on the interface.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-interfaces-primary", "Helsinki Part 9 — Interface", H_P9_IFACE, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Interface exercises."),
        r("java-interfaces-reference", "Defining interfaces", DJ_IFACE, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative interface definition."),
        r("java-interfaces-deep", "Interfaces as a type", DJ_IFACE_TYPE, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Using the interface as the static type."),
    ],
    questions=[
        q("java-interfaces-q1",
          "PaymentProcessor p = new StripeProcessor(); p.pay(100);",
          ["Requires p to be declared StripeProcessor.",
           "Works if StripeProcessor implements PaymentProcessor; the call is dispatched to StripeProcessor.",
           "Always calls a default method only.",
           "Is illegal in Java 21."],
          "Works if StripeProcessor implements PaymentProcessor; the call is dispatched to StripeProcessor.",
          "This is the substitution you will use in backend code.",
          mastery=True),
        q("java-interfaces-q2",
          "Why not new the concrete type in every caller?",
          ["Concrete types cannot have methods.",
           "You couple to one implementation; tests and future providers get harder.",
           "Interfaces are faster.",
           "Helsinki forbids new."],
          "You couple to one implementation; tests and future providers get harder.",
          "Pass the interface into the constructor (simple DI)."),
        q("java-interfaces-q3",
          "default methods exist so:",
          ["Classes cannot implement interfaces.",
           "You can add API methods without breaking every implementor immediately.",
           "Interfaces become abstract classes.",
           "main can live on an interface only."],
          "You can add API methods without breaking every implementor immediately.",
          "Don't dump large implementations into default methods as a design style."),
        q("java-interfaces-q4",
          "A class can implement two interfaces that both declare void close():",
          ["Never compiles.",
           "Compiles if the class provides one compatible close().",
           "Requires two close methods with different names.",
           "Requires multiple inheritance of classes."],
          "Compiles if the class provides one compatible close().",
          "Default-method conflicts need an explicit override."),
        q("java-interfaces-q5",
          "Strategy-like interface means:",
          ["A design where the algorithm is a plug-in object (SortStrategy, Notifier).",
           "A JVM flag.",
           "Only Comparator.",
           "Forbidden in interviews."],
          "A design where the algorithm is a plug-in object (SortStrategy, Notifier).",
          "Comparator is the standard library's famous strategy."),
        q("java-interfaces-q6",
          "Spring Boot is:",
          ["Required to implement an interface.",
           "Out of scope; backend domain later. Interfaces are the language foundation.",
           "The only way to do DI.",
           "A replacement for javac."],
          "Out of scope; backend domain later. Interfaces are the language foundation.",
          "Don't wait for Spring to learn the idea."),
    ],
    exercises=[
        ex("java-interfaces-ex1", "Notifier + payments",
           "interface Notifier { void send(String msg); } EmailNotifier and ConsoleNotifier. "
           "interface PaymentProcessor { boolean pay(int cents); } FakeAlwaysOk and FakeDecline. "
           "A Checkout service that depends on both interfaces (constructor params), not concretes. "
           "In main, swap implementations. Optional: Storage.save(String). No Spring.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-composition",
    hours=0.75,
    objective="Model has-a relationships with composition and keep UI/logic separated where it helps.",
    explanation=(
        "Composition: an object holds another (Car has Engine, Order has List<Line>). "
        "This is the usual has-a tool and often beats inheritance. Helsinki 'objects within objects' plus 'separate UI from logic' is the practical story. "
        + DSA_LIST.split("DSA")[0]
        + "For DSA, a Graph composes lists/maps of nodes; it should not extend HashMap."
    ),
    mastery=[
        "Build a small object that contains another object or collection.",
        "Explain one case where composition beats inheritance.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-composition-primary", "Helsinki Part 6 — Objects within objects", H_P6_WITHIN, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Composition exercises."),
        r("java-composition-reference", "Class design best practices", DJ_DESIGN, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Design guidance; use with the composition lesson."),
        r("java-composition-practice", "Helsinki Part 6 — Separating UI from logic", H_P6_UI, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " Composition of a UI object plus a domain object."),
    ],
    questions=[
        q("java-composition-q1",
          "has-a vs is-a:",
          ["Car is-a Engine.", "Car has-an Engine (composition); Car is-a Vehicle (inheritance) if that is-a is real.",
           "They are synonyms.", "has-a requires extends."],
          "Car has-an Engine (composition); Car is-a Vehicle (inheritance) if that is-a is real.",
          "Most professional Java is composition-heavy.",
          mastery=True),
        q("java-composition-q2",
          "A LinkedList node has a field Node next. That is:",
          ["Inheritance.", "Composition/aggregation of references — the structure of the list.",
           "An interface.", "A static method."],
          "Composition/aggregation of references — the structure of the list.",
          "DSA lists are composition of nodes."),
        q("java-composition-q3",
          "Separating UI from logic helps because:",
          ["Java forbids printing in domain classes.",
           "You can test and reuse domain objects without a Scanner loop.",
           "It makes programs slower.",
           "Helsinki requires JavaFX."],
          "You can test and reuse domain objects without a Scanner loop.",
          "Testing module will thank you."),
        q("java-composition-q4",
          "Extending HashMap to make a School class:",
           ["Great is-a (School is a Map).",
            "Usually wrong: School has students; exposing Map methods leaks representation.",
            "Required for DSA graphs.",
            "The only way to store keys."],
          "Usually wrong: School has students; exposing Map methods leaks representation.",
          "Compose a private Map."),
    ],
    exercises=[
        ex("java-composition-ex1", "Library has Books",
           "Library holds a private List<Book> (or array if List not yet fluent). add, findByTitle, size. "
           "Do not extend ArrayList. Write why not. Optional: a tiny ConsoleUI class that only prints, calling Library methods.",
           difficulty="intermediate"),
    ],
)
