"""Domain 1: Lambdas through Java development practices."""

from __future__ import annotations

from _d1_helpers import (
    DJ_DBG,
    DJ_DESIGN,
    DJ_FI,
    DJ_GC,
    DJ_INTER,
    DJ_IO_FS,
    DJ_IO_INTRO,
    DJ_IO_RW,
    DJ_JAVAC,
    DJ_JAVAP,
    DJ_LAM,
    DJ_MFR,
    DJ_MREF,
    DJ_PKG,
    DJ_STREAMS,
    DJ_TERM,
    DJ_VT,
    H_P4_FILES,
    H_P6_TEST,
    H_P10_STREAM,
    H_P11_FILES,
    H_P11_PKG,
    H_P14_MAVEN,
    HELSINKI_NOTE,
    JUNIT,
    ORACLE_CONC,
    ex,
    q,
    r,
)
from _d1_part3 import CONTENT, _add

_add(
    "java-functional-interfaces",
    hours=0.75,
    objective="Identify a single-abstract-method interface and name the common java.util.function types.",
    explanation=(
        "A functional interface has one abstract method (SAM). @FunctionalInterface documents that. "
        "Predicate, Function, Consumer, Supplier, Comparator are the workhorses. "
        "This is practical Java, not category theory. Not a DSA prerequisite."
    ),
    mastery=[
        "Recognize a SAM and mention Predicate/Function/Consumer.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-functional-interfaces-primary", "Functional interfaces", DJ_FI, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative functional interfaces. Not a DSA gate."),
        r("java-functional-interfaces-practice", "Helsinki Part 10 — Collections as streams", H_P10_STREAM, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Stream material uses lambdas/functional interfaces. Optional practice only."),
    ],
    questions=[
        q("java-functional-interfaces-q1",
          "Runnable is a functional interface because:",
          ["It has many abstract methods.", "It has a single abstract method run().",
           "It is a class.", "It is deprecated."],
          "It has a single abstract method run().",
          "default/static methods do not count as extra abstract methods.",
          mastery=True),
        q("java-functional-interfaces-q2",
          "Predicate<T> represents:",
          ["T → boolean, used for filters.", "void → T.", "T → U.", "int arithmetic."],
          "T → boolean, used for filters.",
          "Function is T → R; Consumer is T → void."),
        q("java-functional-interfaces-q3",
          "Why @FunctionalInterface?",
          ["Required to compile lambdas.",
           "The compiler errors if you accidentally add a second abstract method.",
           "Makes the interface serializable.", "Enables virtual threads."],
          "The compiler errors if you accidentally add a second abstract method.",
          "Lambdas work without the annotation if it is still a SAM."),
        q("java-functional-interfaces-q4",
          "DSA arrays/maps require functional interfaces:",
          ["Yes, always.", "No; they are independent. Functional types help Streams later.",
           "Yes, for HashMap only.", "Yes, for linked lists."],
          "No; they are independent. Functional types help Streams later.",
          "Don't block Domain 2."),
    ],
    exercises=[
        ex("java-functional-interfaces-ex1", "SAM by hand",
           "Write @FunctionalInterface Tripler { int apply(int x); } and a method int twice(Tripler t, int x). "
           "Call it with a small implementing class now (lambda in the next topic). "
           "List Predicate/Function/Consumer/Supplier in comments with one-line meanings."),
    ],
)

_add(
    "java-lambdas",
    hours=1.0,
    objective="Write lambdas and method references for callbacks and collection APIs.",
    explanation=(
        "Lambda: (args) -> body. Captured locals must be effectively final. Method references (String::length) are shorthand. "
        "Use them with List.sort, Iterable.forEach, and later Streams. Not a DSA prerequisite."
    ),
    mastery=[
        "Write a lambda Comparator and a method reference.",
        "Explain effectively final.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-lambdas-primary", "First lambdas", DJ_LAM, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative lambda intro. Not a DSA gate."),
        r("java-lambdas-reference", "Method references", DJ_MREF, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Method reference forms."),
        r("java-lambdas-practice", "Helsinki Part 10 — Collections as streams", H_P10_STREAM, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " Lambdas appear with streams. Keep side-effect-free where possible."),
    ],
    questions=[
        q("java-lambdas-q1",
          "int n = 1; n++; list.forEach(x -> System.out.println(n));",
          ["Always legal.", "Illegal if n is not effectively final (you mutated n).",
           "Prints 1 always.", "Requires n to be static."],
          "Illegal if n is not effectively final (you mutated n).",
          "Capture a copy of a stable local.",
          mastery=True),
        q("java-lambdas-q2",
          "list.sort(Comparator.comparingInt(String::length)) means:",
          ["Illegal method reference.", "Sorts by string length using a method reference.",
           "Mutates each string.", "Requires Streams."],
          "Sorts by string length using a method reference.",
          "Equivalent lambda: (a,b) -> Integer.compare(a.length(), b.length())."),
        q("java-lambdas-q3",
          "Lambdas with side effects (mutating an outer list):",
          ["Best style always.", "Allowed but easy to get wrong; prefer collecting results.",
           "Impossible.", "Required for forEach."],
          "Allowed but easy to get wrong; prefer collecting results.",
          "Streams module will repeat this."),
        q("java-lambdas-q4",
          "Anonymous class vs lambda:",
          ["Lambdas cannot implement SAMs.",
           "Lambda is the short form when all you need is the SAM.",
           "Anonymous classes are illegal after Java 8.",
           "Lambdas can extend classes."],
          "Lambda is the short form when all you need is the SAM.",
          "Need a class with state? Write a class."),
        q("java-lambdas-q5",
          "Block Domain 2 until lambdas are mastered?",
          ["Yes.", "No; this topic is not a DSA gate.",
           "Yes for graphs only.", "Yes for arrays."],
          "No; this topic is not a DSA gate.",
          "You can write Comparator as a class."),
    ],
    exercises=[
        ex("java-lambdas-ex1", "Sort and forEach",
           "List<String> names. Sort by length, then alphabetically, with lambdas or Comparator.comparing. "
           "forEach print. Rewrite length compare as String::length. "
           "Show a compile error from capturing a mutated local."),
    ],
)

_add(
    "java-stream-pipeline",
    hours=1.25,
    objective="Build a stream pipeline: source, intermediate ops, one terminal op.",
    explanation=(
        "A Stream is not a data structure and not an I/O stream. Source → intermediate (lazy) → terminal (eager, consumes). "
        "You can use a pipeline only once. Prefer stateless, side-effect-free intermediates. Not a DSA prerequisite."
    ),
    mastery=[
        "Explain source / intermediate / terminal.",
        "Build one map/filter/collect pipeline.",
        "Avoid depending on side effects for correctness.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-stream-pipeline-primary", "Helsinki Part 10 — Collections as streams", H_P10_STREAM, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Stream exercises. Not a DSA gate. I/O InputStreams are a different concept (File I/O)."),
        r("java-stream-pipeline-reference", "Stream API", DJ_STREAMS, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Official Stream API hub."),
        r("java-stream-pipeline-deep", "Intermediate operations", DJ_INTER, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Laziness of intermediate operations."),
    ],
    questions=[
        q("java-stream-pipeline-q1",
          "list.stream().map(...).filter(...) without a terminal op:",
          ["Runs immediately.", "Does nothing useful; intermediates are lazy until a terminal op.",
           "Throws.", "Sorts the list."],
          "Does nothing useful; intermediates are lazy until a terminal op.",
          "collect/forEach/count/reduce trigger work.",
          mastery=True),
        q("java-stream-pipeline-q2",
          "Reusing a Stream variable after collect:",
          ["Fine always.", "Illegal/throws; a stream is consumed once.",
           "Restarts automatically.", "Converts to I/O."],
          "Illegal/throws; a stream is consumed once.",
          "Create a new stream from the source."),
        q("java-stream-pipeline-q3",
          "Stream API vs java.io streams:",
          ["The same types.",
           "Unrelated: one processes collections in-memory; the other is bytes/chars from I/O.",
           "Both require files.", "Both are DSA gates."],
          "Unrelated: one processes collections in-memory; the other is bytes/chars from I/O.",
          "Preserve this distinction in File I/O."),
        q("java-stream-pipeline-q4",
          "Parallel streams:",
          ["Always faster.",
           "Optional advanced; easy to get wrong with shared mutability; skip for now.",
           "Required for collect.", "Replace HashMap."],
          "Optional advanced; easy to get wrong with shared mutability; skip for now.",
          "Not for DSA."),
        q("java-stream-pipeline-q5",
          "forEach that mutates an outer ArrayList:",
          ["The recommended way to collect.",
           "A side-effect pitfall; use collect(Collectors.toList()).",
           "The only terminal op.",
           "Makes the pipeline lazy forever."],
          "A side-effect pitfall; use collect(Collectors.toList()).",
          "Interviews still ask you to notice this."),
    ],
    exercises=[
        ex("java-stream-pipeline-ex1", "One clean pipeline",
           "From List<Integer>, produce even squares sorted, collected to List. "
           "Comment which ops are intermediate vs terminal. Attempt to reuse the Stream and comment the failure. "
           "Not a DSA prerequisite.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-stream-operations",
    hours=1.25,
    objective="Use map, filter, reduce, collect, grouping, and sorting on streams.",
    explanation=(
        "map transforms, filter keeps, reduce/collect aggregates. groupingBy builds maps. sorted uses Comparator. "
        "Optional appears as findFirst. Keep pipelines readable; don't golf. Not a DSA prerequisite."
    ),
    mastery=[
        "Write map/filter/reduce and a grouping collect.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-stream-operations-primary", "map / filter / reduce", DJ_MFR, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Official map/filter/reduce. Not a DSA gate."),
        r("java-stream-operations-reference", "Terminal operations", DJ_TERM, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Terminal ops including collect/reduce."),
        r("java-stream-operations-practice", "Helsinki Part 10 — Collections as streams", H_P10_STREAM, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE),
    ],
    questions=[
        q("java-stream-operations-q1",
          "filter then map vs map then filter:",
          ["Always identical.",
           "Different: filter first can drop work; the predicate must match the pre-map type.",
           "Illegal to filter after map.", "map cannot change type."],
          "Different: filter first can drop work; the predicate must match the pre-map type.",
          "Choose the order that matches the data.",
          mastery=True),
        q("java-stream-operations-q2",
          "reduce(0, Integer::sum) on boxed ints:",
          ["Always 0.", "Sums; identity 0 is the start value.",
           "Finds max.", "Groups."],
          "Sums; identity 0 is the start value.",
          "collect is often clearer for lists."),
        q("java-stream-operations-q3",
          "Collectors.groupingBy(Person::dept):",
          ["Returns List only.", "Returns Map keyed by dept with lists of people.",
           "Requires PriorityQueue.", "Is an intermediate op."],
          "Returns Map keyed by dept with lists of people.",
          "Terminal collect."),
        q("java-stream-operations-q4",
          "findFirst returns Optional because:",
          ["Streams cannot be empty conceptually.",
           "The stream might be empty; Optional forces you to handle that.",
           "Optional replaces null in all Java.", "findFirst is intermediate."],
          "The stream might be empty; Optional forces you to handle that.",
          "orElse / orElseThrow."),
        q("java-stream-operations-q5",
          "Should you rewrite every for-loop as a stream?",
          ["Yes.", "No; index-heavy DSA loops stay loops.",
           "Yes for DSA only.", "Yes for bytecode."],
          "No; index-heavy DSA loops stay loops.",
          "Two-pointers stay loops."),
        q("java-stream-operations-q6",
          "sorted() on a stream of String:",
          ["Mutates the source list always.",
           "Outputs a new ordered stream; the source list is unchanged unless you collect back.",
           "Uses HashSet order.", "Requires Comparable on Stream itself."],
          "Outputs a new ordered stream; the source list is unchanged unless you collect back.",
          "String is Comparable."),
    ],
    exercises=[
        ex("java-stream-operations-ex1", "Mini dataset",
           "List of simple objects: name, dept, salary. Filter one dept, map names, sort, collect. "
           "groupingBy dept counting. reduce total salary. Print Optional of max salary via max. "
           "No side-effect accumulators. Not a DSA prerequisite.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-paths-files",
    hours=1.0,
    objective="Use Path and Files for existence checks, reading, and writing text.",
    explanation=(
        "java.nio.file.Path locates a file. Files has helpers: exists, readString, writeString, newBufferedReader. "
        "Handle missing files with exceptions or exists checks. This is NIO.2, not the Stream API. "
        "Helsinki file parts may show older File/Scanner styles — prefer Path/Files in new code."
    ),
    mastery=[
        "Read and write a text file via Path/Files.",
        "Handle a missing file without an uncaught crash.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-paths-files-primary", "Java I/O — file system", DJ_IO_FS, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Path and file-system operations. Modern reference."),
        r("java-paths-files-reference", "The Java I/O API", DJ_IO_INTRO, "Dev.java",
          "REFERENCE", "documentation", 1,
          "I/O intro. Distinguishes I/O streams from Stream API."),
        r("java-paths-files-practice", "Helsinki Part 11 — Processing files", H_P11_FILES, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " File exercises; prefer Path/Files locally if Helsinki shows older APIs."),
    ],
    questions=[
        q("java-paths-files-q1",
          "Path vs java.io.File:",
          ["Path is NIO.2's locator type; File is the older class. Prefer Path in new code.",
           "They are the Stream API.",
           "Path only works on Linux.",
           "File is generic."],
          "Path is NIO.2's locator type; File is the older class. Prefer Path in new code.",
          "Don't mix styles randomly in one class.",
          mastery=True),
        q("java-paths-files-q2",
          "Files.readString(path) when the file is missing:",
          ["Returns \"\".", "Throws a checked IOException (typically NoSuchFileException).",
           "Creates the file.", "Returns null."],
          "Throws a checked IOException (typically NoSuchFileException).",
          "Catch at a layer that can tell the user."),
        q("java-paths-files-q3",
          "Relative Path.of(\"data.txt\") is relative to:",
          ["The source file folder always.", "The JVM's working directory.",
           "The JDK install path.", "Git root always."],
          "The JVM's working directory.",
          "Set cwd in the IDE run config if needed."),
        q("java-paths-files-q4",
          "Files.lines(path) vs Stream API on a List:",
          ["Identical types with identical sources.",
           "Files.lines is an I/O-backed stream of lines; List.stream is in-memory. Don't confuse either with InputStream.",
           "Files cannot produce a Stream.",
           "DSA requires Files.lines."],
          "Files.lines is an I/O-backed stream of lines; List.stream is in-memory. Don't confuse either with InputStream.",
          "Close the I/O stream (try-with-resources)."),
    ],
    exercises=[
        ex("java-paths-files-ex1", "Read/write report",
           "Write notes.txt with three lines via Files.writeString. Read it back. Print exists() for a missing path and catch IOException. "
           "Do not ignore the exception. Use the project working directory.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-readers-writers",
    hours=1.0,
    objective="Read and write character data with readers/writers and buffered I/O; contrast byte streams.",
    explanation=(
        "Character streams (Reader/Writer) handle text. Byte streams (InputStream/OutputStream) handle bytes. "
        "Buffering matters for performance. try-with-resources closes them. "
        "This is I/O, not java.util.stream.Stream."
    ),
    mastery=[
        "Read a text file line-by-line and write a report.",
        "Explain character vs byte streams in one paragraph.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-readers-writers-primary", "Reading and writing", DJ_IO_RW, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Official reading/writing tutorial. I/O streams ≠ Stream API."),
        r("java-readers-writers-practice", "Helsinki Part 4 — Files and reading data", H_P4_FILES, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Earlier file-reading exercises; pair with Part 11 processing files."),
        r("java-readers-writers-deep", "Helsinki Part 11 — Processing files", H_P11_FILES, "University of Helsinki",
          "DEEP_DIVE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " More file processing. Prefer modern Path/Files + BufferedReader locally."),
    ],
    questions=[
        q("java-readers-writers-q1",
          "BufferedReader around a FileReader is used because:",
          ["Readers cannot read files otherwise.",
           "Buffering cuts syscalls; readLine is a convenient text API.",
           "It converts to Stream API map/filter.",
           "It makes IOException unchecked."],
          "Buffering cuts syscalls; readLine is a convenient text API.",
          "try-with-resources to close.",
          mastery=True),
        q("java-readers-writers-q2",
          "Byte stream vs character stream:",
          ["They are the same.",
           "Bytes are raw; Readers decode using a charset (UTF-8).",
           "Character streams only work on images.",
           "Byte streams cannot be buffered."],
          "Bytes are raw; Readers decode using a charset (UTF-8).",
          "Don't read UTF-8 text as raw bytes then hope."),
        q("java-readers-writers-q3",
          "try (BufferedReader br = Files.newBufferedReader(path)) { ... }:",
          ["Leaks the file always.", "Closes the reader even on exception.",
           "Is illegal.", "Disables exceptions."],
          "Closes the reader even on exception.",
          "Prefer this over manual finally."),
        q("java-readers-writers-q4",
          "Parsing structured text (CSV-like) should:",
          ["Ignore malformed lines silently always.",
           "Validate fields; skip or report bad lines explicitly.",
           "Use catch Exception in the inner loop as the parser.",
           "Require Spring."],
          "Validate fields; skip or report bad lines explicitly.",
          "Same discipline as console I/O."),
    ],
    exercises=[
        ex("java-readers-writers-ex1", "Parse and report",
           "Create scores.csv with name,score rows including one bad line. Read with BufferedReader, skip/report the bad line, "
           "write report.txt with average and count. try-with-resources. Comment: I/O stream ≠ Stream API.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-junit-basics",
    hours=1.0,
    objective="Run a JUnit test class and explain why tests exist.",
    explanation=(
        "A unit test checks one behavior of a method with a clear name. JUnit runs methods annotated @Test. "
        "Tests should be independent. Helsinki introduces testing; JUnit 5 docs are the modern runner reference. "
        "This is not a full testing-career course."
    ),
    mastery=[
        "Write and run at least two JUnit tests for a utility method.",
        "Explain isolation and naming.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-junit-basics-primary", "Helsinki Part 6 — Introduction to testing", H_P6_TEST, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Testing ideas and exercises. Tooling may differ; run JUnit 5 locally (Maven/Gradle or IDE)."),
        r("java-junit-basics-reference", "JUnit 5 User Guide", JUNIT, "JUnit",
          "REFERENCE", "documentation", 1,
          "Official JUnit 5 guide. Dev.java has no JUnit chapter; this is the canonical test-framework reference."),
    ],
    questions=[
        q("java-junit-basics-q1",
          "Why write tests instead of only running main?",
          ["main cannot call methods.",
           "Tests pin behavior, rerun cheaply, and document edge cases.",
           "JUnit replaces the compiler.",
           "Tests make exceptions illegal."],
          "Tests pin behavior, rerun cheaply, and document edge cases.",
          "DSA later: test a method, not a print loop.",
          mastery=True),
        q("java-junit-basics-q2",
          "Tests sharing a mutable static counter:",
          ["Fine isolation.", "Breaks isolation; order can flake.",
           "Required by JUnit.", "Faster always."],
          "Breaks isolation; order can flake.",
          "Each test sets up its own data."),
        q("java-junit-basics-q3",
          "@Test void foo() with no assertions:",
          ["A strong test.", "Passes even if the code is wrong — assertions needed.",
           "Does not compile.", "Runs in production automatically."],
          "Passes even if the code is wrong — assertions needed.",
          "Next topic is assertions."),
        q("java-junit-basics-q4",
          "Naming testWithdrawInsufficientFunds:",
          ["Too long; use t1.", "Describes the scenario; helpful when it fails.",
           "Illegal underscores.", "Must match the production method exactly."],
          "Describes the scenario; helpful when it fails.",
          "Read the test name in the failure list."),
    ],
    exercises=[
        ex("java-junit-basics-ex1", "Test a utility",
           "Write StringUtils.isBlank and MathUtils.clamp. Add a JUnit 5 test class with at least four tests. "
           "Run via IDE or `mvn test` if you already have Maven (otherwise IDE JUnit run). "
           "Helsinki testing exercises are optional extra reps.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-assertions",
    hours=0.5,
    objective="Use JUnit assertions for return values and thrown exceptions, including boundaries.",
    explanation=(
        "assertEquals, assertTrue, assertThrows check outcomes. Test boundaries (0, empty, max). "
        "Java's `assert` keyword is a different, usually-off mechanism — do not confuse it with JUnit. "
        "Write tests before or after implementation; the point is the spec."
    ),
    mastery=[
        "Assert a return value and an exception.",
        "Add at least one boundary case.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-assertions-primary", "JUnit 5 User Guide", JUNIT, "JUnit",
          "PRIMARY", "documentation", 0,
          "Assertions live in the official JUnit 5 user guide. Use the writing-tests / assertions sections."),
        r("java-assertions-practice", "Helsinki Part 6 — Introduction to testing", H_P6_TEST, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Testing exercises; map assertions onto JUnit 5 locally."),
    ],
    questions=[
        q("java-assertions-q1",
          "assertThrows(IllegalArgumentException.class, () -> clamp(1, 5, 0)):",
          ["Fails if no exception or the wrong type is thrown.",
           "Passes if any exception is thrown.",
           "Is the Java assert keyword.",
           "Compiles the production class."],
          "Fails if no exception or the wrong type is thrown.",
          "This is how you test guards.",
          mastery=True),
        q("java-assertions-q2",
          "assertEquals(expected, actual) argument order:",
          ["Does not matter for the message.",
           "Convention: expected first so failure messages read correctly.",
           "actual must be a String.",
           "Equals uses == for strings."],
          "Convention: expected first so failure messages read correctly.",
          "Use assertEquals for objects that implement equals."),
        q("java-assertions-q3",
          "Boundary for indexOf on \"\" :",
          ["Uninteresting.", "Empty string is a classic edge; assert the documented result.",
           "JUnit forbids empty strings.", "Must throw always."],
          "Empty string is a classic edge; assert the documented result.",
          "Also: 0, -1, Integer.MAX_VALUE when relevant."),
        q("java-assertions-q4",
          "Java `assert x > 0;` vs JUnit:",
          ["Identical, always on.",
           "assert may be disabled unless -ea; JUnit assertions always run in tests.",
           "JUnit is disabled by default.",
           "Both replace exceptions."],
          "assert may be disabled unless -ea; JUnit assertions always run in tests.",
          "Use JUnit in tests; don't rely on -ea in production."),
    ],
    exercises=[
        ex("java-assertions-ex1", "Boundaries first",
           "For clamp(min, max, n): test n==min, n==max, n<min, n>max, and min>max throws. Use assertEquals and assertThrows. "
           "Optionally write failing tests first, then implement."),
    ],
)

_add(
    "java-threads",
    hours=1.25,
    objective="Start work on another thread (Runnable/Executor) and contrast process vs thread.",
    explanation=(
        "A process is an OS program instance. A thread is a unit of execution inside a process sharing memory. "
        "Runnable is the task; Thread/Executor runs it. ExecutorService is the modern default over raw new Thread. "
        "Virtual threads (Dev.java) are a modern scaling feature — reference only, not a DSA gate. "
        "Helsinki does not map to a verified concurrency part here."
    ),
    mastery=[
        "Explain process vs thread.",
        "Submit a Runnable to an executor or start a Thread and join it.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-threads-primary", "Oracle concurrency tutorial", ORACLE_CONC, "Oracle",
          "PRIMARY", "documentation", 0,
          "Official Java Tutorial concurrency trail (processes/threads, Runnable). Dev.java has no basic Thread chapter; this is the verified official substitute."),
        r("java-threads-deep", "Virtual threads", DJ_VT, "Dev.java",
          "DEEP_DIVE", "documentation", 1,
          "Modern virtual threads: what/why/how. Not a DSA prerequisite. Do not start here."),
    ],
    questions=[
        q("java-threads-q1",
          "Two threads in one JVM share:",
          ["Nothing.", "The heap (and thus objects) — which is why races exist.",
           "Separate heaps always.", "Only stdout."],
          "The heap (and thus objects) — which is why races exist.",
          "Synchronization is the next topic.",
          mastery=True),
        q("java-threads-q2",
          "new Thread(runnable).start() vs .run():",
          ["Identical.", "start schedules a new thread; run executes on the current thread.",
           "run is illegal.", "start compiles the class."],
          "start schedules a new thread; run executes on the current thread.",
          "A common bug: calling run() by mistake."),
        q("java-threads-q3",
          "ExecutorService vs raw Thread:",
          ["Executor is deprecated.",
           "Executors reuse workers and manage lifecycle; prefer them for real code.",
           "Threads cannot run Runnable.",
           "Executors require Spring."],
          "Executors reuse workers and manage lifecycle; prefer them for real code.",
          "Remember shutdown()."),
        q("java-threads-q4",
          "CompletableFuture is:",
          ["Required for HashMap.",
           "A composition API for async results — conceptual awareness only here.",
           "A List.",
           "A DSA gate."],
          "A composition API for async results — conceptual awareness only here.",
          "Don't build a future framework in this topic."),
        q("java-threads-q5",
          "Virtual threads should be learned as:",
          ["A prerequisite for arrays.",
           "A modern reference for scaling blocking I/O — after core thread/race ideas.",
           "A replacement for the JVM.",
           "Mandatory for PriorityQueue."],
          "A modern reference for scaling blocking I/O — after core thread/race ideas.",
          "Not for Domain 2."),
    ],
    exercises=[
        ex("java-threads-ex1", "Two workers",
           "Print 50 lines from the main thread and 50 from a second thread (Runnable + start/join or an ExecutorService with shutdown/awaitTermination). "
           "Observe interleaving. One paragraph: process vs thread. Do not skip the race in the next topic. Not a DSA gate.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-synchronization-basics",
    hours=1.25,
    objective="Demonstrate a race and fix it with synchronized/locking; explain visibility at a high level.",
    explanation=(
        "A race: two threads update shared mutable state with no happens-before. synchronized / locks make a critical section. "
        "Visibility: without synchronization, another thread may never see your write. "
        "Concurrent collections exist; don't roll a concurrent HashMap by hand. Not a DSA algorithms course."
    ),
    mastery=[
        "Show a race (counter++) and a synchronized fix.",
        "Identify unsafe shared mutation.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-synchronization-basics-primary", "Oracle concurrency tutorial", ORACLE_CONC, "Oracle",
          "PRIMARY", "documentation", 0,
          "Synchronization, liveness, and guarded blocks in the official trail. Same URL as threads — read the synchronization sections."),
        r("java-synchronization-basics-reference", "Virtual threads", DJ_VT, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Modern threading model awareness. Does not replace understanding races."),
    ],
    questions=[
        q("java-synchronization-basics-q1",
          "count++ from two threads without sync:",
          ["Always exact.", "Can lose updates (read-modify-write is not atomic).",
           "Is atomic for int always.", "Deadlocks always."],
          "Can lose updates (read-modify-write is not atomic).",
          "Demonstrate, then fix.",
          mastery=True),
        q("java-synchronization-basics-q2",
          "synchronized methods on the same object:",
          ["Run fully concurrently always.", "Exclude each other on that monitor.",
           "Make the class immutable.", "Replace the JVM memory model."],
          "Exclude each other on that monitor.",
          "Different objects → different locks."),
        q("java-synchronization-basics-q3",
          "Visibility in one sentence:",
          ["Disk cache.", "Without a sync barrier, a reader thread may see stale field values.",
           "Only applies to C++.", "GC visibility."],
          "Without a sync barrier, a reader thread may see stale field values.",
          "volatile is a narrower tool; don't start there."),
        q("java-synchronization-basics-q4",
          "catch (Exception) around a race:",
          ["Fixes races.", "Does not make compound actions atomic.",
           "Is required for synchronized.", "Stops the JIT."],
          "Does not make compound actions atomic.",
          "Exceptions ≠ locks."),
        q("java-synchronization-basics-q5",
          "ConcurrentHashMap vs synchronizing every HashMap call:",
          ["Identical always.",
           "CHM is designed for concurrent use; a wrapped HashMap needs a consistent lock story.",
           "HashMap is already safe.",
           "Maps cannot be concurrent."],
          "CHM is designed for concurrent use; a wrapped HashMap needs a consistent lock story.",
          "Still not a DSA prerequisite."),
    ],
    exercises=[
        ex("java-synchronization-basics-ex1", "Break then fix a counter",
           "Two threads increment a shared int 100_000 times each without sync; print vs 200_000. "
           "Fix with synchronized or AtomicInteger. Comment which object you locked. "
           "Not a concurrent-algorithms course.",
           difficulty="intermediate"),
    ],
)

_add(
    "java-bytecode",
    hours=0.75,
    objective="Explain .class as JVM bytecode and inspect it lightly with javap.",
    explanation=(
        "javac emits bytecode in .class files. The JVM loads classes and executes bytecode (then JIT may compile hot methods to native). "
        "javap -c disassembles. You do not need to memorize opcodes."
    ),
    mastery=[
        "Run javap on a small class and relate it to source.",
        "Explain class file vs source vs JIT at a high level.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-bytecode-primary", "javap — Core JDK tools", DJ_JAVAP, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Official javap page for inspecting class files."),
        r("java-bytecode-reference", "javac", DJ_JAVAC, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Compiler front of the pipeline. Getting Started already covered the cycle."),
    ],
    questions=[
        q("java-bytecode-q1",
          "A .class file contains:",
          ["UTF-16 source.", "JVM bytecode (and metadata), not your original comments as comments.",
           "A Windows .exe only.", "SQL."],
          "JVM bytecode (and metadata), not your original comments as comments.",
          "javap shows the bytecode.",
          mastery=True),
        q("java-bytecode-q2",
          "Class loading is:",
          ["Copying RAM into disk.", "The JVM locating and linking .class bytes into a usable class.",
           "javac only.", "Git fetch."],
          "The JVM locating and linking .class bytes into a usable class.",
          "Wrong classpath → NoClassDefFoundError / ClassNotFoundException."),
        q("java-bytecode-q3",
          "JIT means:",
          ["The interpreter is deleted on install.",
           "Hot methods may be compiled to native code at runtime for speed.",
           "You must run javap before java.",
           "Bytecode is never executed."],
          "Hot methods may be compiled to native code at runtime for speed.",
          "That's why warm-up exists in benchmarks."),
        q("java-bytecode-q4",
          "Do you need bytecode to write DSA?",
          ["Yes, every solution.", "No; it explains how Java runs.",
           "Yes, for arrays only.", "Yes, for HashMap."],
          "No; it explains how Java runs.",
          "Not a DSA gate."),
    ],
    exercises=[
        ex("java-bytecode-ex1", "javap a method",
           "Write a class with a small add(int,int). javac it. Run `javap -c ClassName` and paste 5–10 lines of output into comments. "
           "Circle (in comments) that you see an iadd or similar. No opcode memorization."),
    ],
)

_add(
    "java-memory-model-basics",
    hours=0.75,
    objective="Name heap vs stack at a Java programmer level and place objects vs frames.",
    explanation=(
        "Each method call has a stack frame (locals, including references). Objects live on the heap (programmer model). "
        "The Java Memory Model also defines visibility between threads — you saw that in synchronization. "
        "There is no dedicated Dev.java 'heap vs stack' chapter; this is an internal lesson plus GC as heap context. "
        "Not JVM internals / not a DSA gate."
    ),
    mastery=[
        "Sketch stack frames pointing at heap objects for a short program.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-memory-model-basics-reference", "Garbage collection overview", DJ_GC, "Dev.java",
          "REFERENCE", "documentation", 0,
          "GC runs on heap objects. No verified PRIMARY course URL for stack-vs-heap; the lesson text is authoritative here."),
    ],
    questions=[
        q("java-memory-model-basics-q1",
          "int x = 3; in a method typically lives:",
          ["On the heap as an Integer always.", "In the stack frame as a primitive local.",
           "In the .java file at runtime.", "In the instruction cache only."],
          "In the stack frame as a primitive local.",
          "Integer.valueOf(3) would be a heap object.",
          mastery=True),
        q("java-memory-model-basics-q2",
          "Node n = new Node():",
          ["The Node object is on the heap; n (the reference) is in the frame.",
           "The entire object is in CPU registers forever.",
           "n is stored in the .class constant pool only.",
           "Java has no heap."],
          "The Node object is on the heap; n (the reference) is in the frame.",
          "Linked lists are heap graphs."),
        q("java-memory-model-basics-q3",
          "Escape / 'memory model' between threads:",
          ["Stack frames are shared by all threads always.",
           "Each thread has its own stack; the heap is shared — hence races.",
           "Heaps are per-thread and never shared.",
           "GC disables threads."],
          "Each thread has its own stack; the heap is shared — hence races.",
          "Enough for this curriculum."),
        q("java-memory-model-basics-q4",
          "Why this is not a JVM-spec course:",
           ["Programmers need a model for NPE, GC, and races — not interpreter source.",
            "You must implement a JVM.",
            "DSA requires compressed oops.",
            "Helsinki Part 14 is the JVM spec."],
          "Programmers need a model for NPE, GC, and races — not interpreter source.",
          "Stop at the picture you can draw."),
    ],
    exercises=[
        ex("java-memory-model-basics-ex1", "Draw the frames",
           "Write method a() { Box b = new Box(); c(b); } method c(Box x) { x.v++; }. "
           "ASCII-draw: frames a and c, heap Box, both references. Mark what ++ mutates. No PRIMARY URL exists for this picture — that is expected."),
    ],
)

_add(
    "java-gc-intro",
    hours=0.75,
    objective="Explain reachability and that GC reclaims unreachable objects.",
    explanation=(
        "Garbage collection frees heap objects that are not reachable from GC roots (stacks, statics, etc.). "
        "You don't call free(). Memory leaks in Java are usually accidental retained references. "
        "Tuning collectors is out of scope. Profiling awareness: jcmd/JFR exist; you don't need them daily yet."
    ),
    mastery=[
        "Explain reachability vs leak via a lingering static list.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-gc-intro-primary", "Garbage collection overview", DJ_GC, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Official GC overview. Do not tune G1/ZGC here."),
    ],
    questions=[
        q("java-gc-intro-q1",
          "An object is eligible for GC when:",
          ["The constructor finishes.", "No GC root can reach it.",
           "It goes out of the source file.", "You print it."],
          "No GC root can reach it.",
          "Cycles of unreachable objects can still be collected.",
          mastery=True),
        q("java-gc-intro-q2",
          "static List<byte[]> cache that only grows:",
          ["Helps GC.", "A retention leak: objects stay reachable.",
           "Required for HashMap.", "Frees memory automatically still."],
          "A retention leak: objects stay reachable.",
          "GC cannot collect what you still point at."),
        q("java-gc-intro-q3",
          "System.gc():",
          ["Guarantees a full collection now.", "A suggestion; not a resource-management API.",
           "Closes files.", "Stops the world forever."],
          "A suggestion; not a resource-management API.",
          "Don't write System.gc() in app code as a habit."),
        q("java-gc-intro-q4",
          "Profiling awareness means:",
          ["You must master JFR this week.",
           "You know tools exist (JFR, VisualVM, etc.) when allocation is actually a problem.",
           "GC replaces Big-O.",
           "DSA requires GC tuning."],
          "You know tools exist (JFR, VisualVM, etc.) when allocation is actually a problem.",
          "Not a DSA gate."),
    ],
    exercises=[
        ex("java-gc-intro-ex1", "Reachability paragraph",
           "Write 8–10 sentences: roots, reachable objects, a leak via a static collection, why unused locals can be GC'd after last use (conceptually). "
           "Optional: after javap topic, note that allocation is `new` in bytecode. Do not tune flags."),
    ],
)

_add(
    "java-packages",
    hours=0.75,
    objective="Organize classes into packages and import them.",
    explanation=(
        "Packages are namespaces that match directory structure. com.example.util.Strings lives in com/example/util/Strings.java. "
        "import names types; wildcard imports are optional. Not a DSA prerequisite."
    ),
    mastery=[
        "Create two packages and import across them.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-packages-primary", "Helsinki Part 11 — Packages", H_P11_PKG, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Package exercises. Not a DSA gate."),
        r("java-packages-reference", "Packages", DJ_PKG, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative packages tutorial."),
    ],
    questions=[
        q("java-packages-q1",
          "package app.core; public class A in file A.java should live in:",
          ["any folder.", "folder app/core.",
           "the JDK lib folder.", "the default package only."],
          "folder app/core.",
          "The compiler and classpath expect that layout.",
          mastery=True),
        q("java-packages-q2",
          "import app.core.A vs using fully qualified names:",
          ["import copies the class.", "import is a shorthand so you can write A instead of app.core.A.",
           "import is required for String.", "import runs the class."],
          "import is a shorthand so you can write A instead of app.core.A.",
          "java.lang is imported automatically."),
        q("java-packages-q3",
          "Default (no package) classes:",
          ["Best for large projects.", "Fine for tiny exercises; painful once you have two libs named Util.",
           "Required by JUnit.", "The only way to use javac."],
          "Fine for tiny exercises; painful once you have two libs named Util.",
          "Start packaging when more than a handful of classes."),
        q("java-packages-q4",
          "Modules (JPMS) in this topic:",
          ["Required now.", "Later/reference; packages are enough.",
           "Replace packages.", "A DSA gate."],
          "Later/reference; packages are enough.",
          "Don't block backend on module-info."),
    ],
    exercises=[
        ex("java-packages-ex1", "Two packages",
           "app.model.Box and app.Main that imports Box. Compile from the source root so package folders match. "
           "Record the javac command you used. Not a DSA gate."),
    ],
)

_add(
    "java-api-hygiene",
    hours=1.5,
    objective="Ship a small tidy Java project: packages, build tool awareness, naming, tests, formatting, logging/debug.",
    explanation=(
        "Professional Java: clear names, small methods, immutability where it helps, no Spring Boot yet. "
        "Maven (Helsinki Part 14) or Gradle builds, tests, and dependencies. Format/lint in the editor. "
        "Logging > println in apps; debugger > guess-and-print. Code review is reading diffs for intent. "
        "Records/modules/virtual threads stay reference — not required here."
    ),
    mastery=[
        "Put a tiny library + tests in a Maven or Gradle layout (or document equivalent IDE project).",
        "Refactor one bloated method; name things clearly.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-api-hygiene-primary", "Helsinki Part 14 — Maven and third-party libraries", H_P14_MAVEN, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Maven/deps. Gradle awareness is conceptual if you do not open a Gradle page here. No Spring Boot."),
        r("java-api-hygiene-reference", "Class design best practices", DJ_DESIGN, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Design/naming/API shape."),
        r("java-api-hygiene-deep", "Debugging", DJ_DBG, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Official debugger tutorial. Use breakpoints instead of only println."),
    ],
    questions=[
        q("java-api-hygiene-q1",
          "A 80-line method that parses, computes, and prints:",
          ["High cohesion.", "Should be split; names should say what each part does.",
           "Required by Maven.", "Better for GC."],
          "Should be split; names should say what each part does.",
          "Hygiene is readability for future you.",
          mastery=True),
        q("java-api-hygiene-q2",
          "Spring Boot belongs:",
          ["In this topic as a required dependency.", "In a future Backend domain.",
           "Inside javac.", "As a DSA prerequisite."],
          "In a future Backend domain.",
          "You can write Java without Spring."),
        q("java-api-hygiene-q3",
          "Logging vs System.out:",
          ["Identical.", "Loggers have levels and can be turned down in production.",
           "Logging is illegal in Java.", "println is a JUnit assertion."],
          "Loggers have levels and can be turned down in production.",
          "java.util.logging or a later library — awareness is enough."),
        q("java-api-hygiene-q4",
          "Immutable objects help because:",
          ["They use no memory.", "Sharing references is safer when state cannot change.",
           "Java forbids mutation.", "GC is disabled."],
          "Sharing references is safer when state cannot change.",
          "Records are a later concise form — optional."),
        q("java-api-hygiene-q5",
          "Maven/Gradle exist to:",
          ["Replace the JDK.", "Declare dependencies and run compile/test in a standard layout.",
           "Execute bytecode instead of the JVM.", "Teach C++."],
          "Declare dependencies and run compile/test in a standard layout.",
          "Pick one; don't learn both deeply this week."),
        q("java-api-hygiene-q6",
          "A code review looks for:",
          ["Only formatting nits.", "Correctness, naming, tests, and accidental complexity.",
           "Whether Spring is used.", "Line count above 500 as a goal."],
          "Correctness, naming, tests, and accidental complexity.",
          "Formatters handle bikesheds."),
    ],
    exercises=[
        ex("java-api-hygiene-ex1", "Tiny professional project",
           "Create a small Maven (preferred, Helsinki Part 14) or Gradle project: package app.util, a StringStats class, JUnit tests, "
           "README with how to test. Format the code (editor formatter). Set a debugger breakpoint once. "
           "No Spring Boot. If Maven XML is new, follow Helsinki's Maven section plus your JDK — not a random blog. "
           "This closes Domain 1; it does not start Domain 2.",
           difficulty="intermediate"),
    ],
)
