"""Domain 1: Exceptions through Comparable/Comparator."""

from __future__ import annotations

from _d1_helpers import (
    CMP_API,
    DJ_AL_LL,
    DJ_COL_INTRO,
    DJ_COMP_LAM,
    DJ_ERASE,
    DJ_EX_CATCH,
    DJ_EX_THROW,
    DJ_EX_WHAT,
    DJ_GEN,
    DJ_ITER,
    DJ_LISTS,
    DJ_MAPS,
    DJ_QQ,
    DJ_SETS,
    DJ_WILD,
    DSA_HEAP,
    DSA_LIST,
    DSA_MAP,
    DSA_SET,
    H_P3_LISTS,
    H_P8_GROUP,
    H_P8_MAP,
    H_P10_COMP,
    H_P11_EX,
    H_P12_GEN,
    HELSINKI_NOTE,
    PQ_API,
    ex,
    q,
    r,
)
from _d1_part2 import CONTENT, _add

_add(
    "java-try-catch",
    hours=1.0,
    objective="Handle recoverable failures with try/catch/finally without swallowing everything.",
    explanation=(
        "Exceptions signal that a method cannot complete normally. try/catch handles a specific type you can recover from. "
        "finally runs for cleanup. Prefer try-with-resources for Closeable I/O (File I/O module). "
        "Do not catch Exception everywhere. Empty catch blocks hide bugs."
    ),
    mastery=[
        "Write try/catch for a recoverable error and a finally or try-with-resources note.",
        "Explain why catch (Exception e) {} is usually wrong.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-try-catch-primary", "Helsinki Part 11 — Exceptions", H_P11_EX, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Exception exercises."),
        r("java-try-catch-reference", "Catching and handling exceptions", DJ_EX_CATCH, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative try/catch/finally."),
    ],
    questions=[
        q("java-try-catch-q1",
          "catch (NumberFormatException e) after Integer.parseInt:",
          ["Hides all bugs in the program.",
           "Is appropriate if you can re-prompt the user for a number.",
           "Must rethrow always.",
           "Is illegal."],
          "Is appropriate if you can re-prompt the user for a number.",
          "Recoverable input error.",
          mastery=True),
        q("java-try-catch-q2",
          "catch (Exception e) { } with an empty body:",
          ["Best practice.", "Swallows failures including bugs; later code runs as if nothing happened.",
           "Required by javac.", "Faster than logging."],
          "Swallows failures including bugs; later code runs as if nothing happened.",
          "If you catch, log or recover. Don't vanish."),
        q("java-try-catch-q3",
          "finally runs:",
          ["Only on success.", "On success and on exception (unless JVM dies), so it is for cleanup.",
           "Only if you return in catch.", "Never if you return in try."],
          "On success and on exception (unless JVM dies), so it is for cleanup.",
          "It even runs when try returns — which surprises people."),
        q("java-try-catch-q4",
          "Exceptions for ordinary control flow (e.g. expected empty optional):",
          ["Idiomatic Java always.",
           "Usually the wrong tool; use return values/Optional/if for expected cases.",
           "Required for loops.",
           "Faster than if."],
          "Usually the wrong tool; use return values/Optional/if for expected cases.",
          "Exceptions are for exceptional paths."),
        q("java-try-catch-q5",
          "Multi-catch catch (A | B e):",
          ["Handles either type in one block when recovery is the same.",
           "Creates two exception objects.",
           "Is a switch expression.",
           "Only works for Error."],
          "Handles either type in one block when recovery is the same.",
          "Keep the union small and related."),
    ],
    exercises=[
        ex("java-try-catch-ex1", "Validate, don't swallow",
           "CLI: parse integers until \"done\". On bad tokens, catch NumberFormatException, print a useful message, continue. "
           "Add a finally that prints \"session end\" (or use try-with-resources if you open a Scanner on a file in a later pass). "
           "Do not catch Exception. "
           + HELSINKI_NOTE,
           difficulty="intermediate"),
    ],
)

_add(
    "java-checked-unchecked",
    hours=0.75,
    objective="Distinguish checked vs unchecked exceptions and choose throws vs handle.",
    explanation=(
        "Unchecked: RuntimeException and Error — compiler does not require catch/throws (NPE, IAE, IOBE). "
        "Checked: other Exception subclasses — callers must catch or declare throws (classic IOException). "
        "APIs disagree on how much checked is good; don't invent checked exceptions for every domain miss. "
        "Propagation: if you cannot handle it, declare throws or wrap."
    ),
    mastery=[
        "Classify NPE vs IOException.",
        "Write a method that declares throws for a checked exception it does not handle.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-checked-unchecked-primary", "What is an exception?", DJ_EX_WHAT, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Exception hierarchy and the idea of exceptional events."),
        r("java-checked-unchecked-reference", "Throwing exceptions", DJ_EX_THROW, "Dev.java",
          "REFERENCE", "documentation", 1,
          "throw, throws, and creating exceptions."),
        r("java-checked-unchecked-practice", "Helsinki Part 11 — Exceptions", H_P11_EX, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " File/exception interplay appears in Part 11."),
    ],
    questions=[
        q("java-checked-unchecked-q1",
          "NullPointerException is:",
          ["Checked; you must declare throws NPE.",
           "Unchecked (RuntimeException); the compiler does not force you to catch it.",
           "An Error only.",
           "Not an exception."],
          "Unchecked (RuntimeException); the compiler does not force you to catch it.",
          "Fix the null; don't catch NPE as a style.",
          mastery=True),
        q("java-checked-unchecked-q2",
          "A method that calls a checked-throwing API and does not catch must:",
          ["Ignore it.", "Declare throws of that checked type (or a supertype).",
           "Be native.", "Use var."],
          "Declare throws of that checked type (or a supertype).",
          "The compiler tracks checked exceptions."),
        q("java-checked-unchecked-q3",
          "Wrapping a checked exception in a RuntimeException is:",
          ["Always evil.",
           "A common way to propagate when your layer cannot handle I/O but does not want throws on every method — use deliberately.",
           "Required by HashMap.",
           "The same as swallowing."],
          "A common way to propagate when your layer cannot handle I/O but does not want throws on every method — use deliberately.",
          "Preserve the cause (e.initCause / constructor)."),
        q("java-checked-unchecked-q4",
          "Error (OutOfMemoryError) should be:",
          ["Caught in every method.", "Generally not caught; the JVM is in trouble.",
           "Treated as checked.", "Used for validation."],
          "Generally not caught; the JVM is in trouble.",
          "Don't write catch (Throwable t) as a habit."),
        q("java-checked-unchecked-q5",
          "Layered propagation means:",
          ["UI catches, logs, shows a message; domain throws; low-level I/O throws IOException.",
           "Every layer must catch and ignore.",
           "Only main can throw.",
           "Checked exceptions cannot cross packages."],
          "UI catches, logs, shows a message; domain throws; low-level I/O throws IOException.",
          "Handle at the layer that can actually decide."),
    ],
    exercises=[
        ex("java-checked-unchecked-ex1", "throws vs handle",
           "Write readFirstLine(Path p) throws IOException using Files.readString or a BufferedReader (see File I/O pages if needed). "
           "Write greetUser() that calls it and catch IOException to print 'missing file' without declaring throws. "
           "List in comments: NPE, IAE, IOException, Error — checked or not."),
    ],
)

_add(
    "java-custom-exceptions",
    hours=0.75,
    objective="Define a small domain exception and throw it at an invariant boundary.",
    explanation=(
        "A custom exception is a type that names a domain failure (InsufficientFundsException). "
        "Extend RuntimeException unless you have a strong reason for checked. Include a message and optionally a cause. "
        "Throw at the boundary; don't use exceptions for normal returns."
    ),
    mastery=[
        "Write a custom exception and throw it from a domain method.",
        "Catch it at a layer that can talk to the user.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-custom-exceptions-primary", "Throwing exceptions", DJ_EX_THROW, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Creating and throwing exceptions, including custom types."),
        r("java-custom-exceptions-practice", "Helsinki Part 11 — Exceptions", H_P11_EX, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Use Part 11 exercises; add a custom type locally if Helsinki does not require one."),
    ],
    questions=[
        q("java-custom-exceptions-q1",
          "InsufficientFundsException extends RuntimeException so that:",
          ["Callers are forced to catch it everywhere.",
           "It is unchecked; callers can still catch it at the UI.",
           "It becomes an Error.",
           "It cannot have a message."],
          "It is unchecked; callers can still catch it at the UI.",
          "Domain failures are often unchecked.",
          mastery=True),
        q("java-custom-exceptions-q2",
          "new Exception() with no name/message:",
          ["Ideal API.", "Hard to diagnose; name the type and message.",
           "Faster.", "Required."],
          "Hard to diagnose; name the type and message.",
          "Types are documentation."),
        q("java-custom-exceptions-q3",
          "Throwing on a failed withdraw vs returning boolean:",
          ["Throwing is always better.",
           "Choose: boolean/optional for expected failure; exception if the caller should not continue with a half-updated account.",
           "Must throw checked.",
           "Must never throw."],
          "Choose: boolean/optional for expected failure; exception if the caller should not continue with a half-updated account.",
          "Be consistent in one codebase."),
        q("java-custom-exceptions-q4",
          "catch (InsufficientFundsException e) in the same method that threw it:",
          ["Often pointless; throw from the guard and catch higher.",
           "Required.",
           "The only legal catch.",
           "Disables GC."],
          "Often pointless; throw from the guard and catch higher.",
          "Don't catch just because you can."),
    ],
    exercises=[
        ex("java-custom-exceptions-ex1", "Domain exception on BankAccount",
           "Add InsufficientFundsException. withdraw throws it. main catch prints a user-facing line. "
           "Do not catch Exception. Optional: cause-wrapping if you convert a NumberFormatException in a parser."),
    ],
)

_add(
    "java-list",
    hours=1.5,
    objective="Choose List implementations (usually ArrayList) and use them for ordered sequences.",
    explanation=(
        "List is an ordered Collection. ArrayList is a resizable array (C++ vector). LinkedList is a doubly linked list — rarely the default. "
        "Program to List, construct ArrayList. Indexing ArrayList is O(1); adding at the end is amortized O(1). "
        "Helsinki Part 3 lists are ArrayList-heavy. "
        + DSA_LIST
        + " Domain 2 stack/queue topics still need classes + references; List is the usual Java backbone."
    ),
    mastery=[
        "Use List/ArrayList for add, get, iterate, and size.",
        "Explain when ArrayList beats LinkedList for access patterns.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-list-primary", "Helsinki Part 3 — Lists", H_P3_LISTS, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " ArrayList exercises. " + DSA_LIST),
        r("java-list-reference", "List interface", DJ_LISTS, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative List tutorial."),
        r("java-list-deep", "ArrayList vs LinkedList", DJ_AL_LL, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Choose by access pattern. Default: ArrayList."),
    ],
    questions=[
        q("java-list-q1",
          "Why declare List<String> names = new ArrayList<>()?",
          ["List cannot be constructed any other way.",
           "Code depends on the List contract; you can swap implementation later.",
           "ArrayList is an interface.",
           "Generics require the interface on the right."],
          "Code depends on the List contract; you can swap implementation later.",
          "new List<>() is illegal because List is an interface.",
          mastery=True),
        q("java-list-q2",
          "Random get(i) on ArrayList vs LinkedList:",
          ["Both O(1).", "ArrayList O(1); LinkedList O(n).",
           "LinkedList O(1); ArrayList O(n).", "Both O(n^2)."],
          "ArrayList O(1); LinkedList O(n).",
          "If you index a lot, don't pick LinkedList."),
        q("java-list-q3",
          "C++ vector analogue is:",
          ["HashMap", "ArrayList", "Thread", "enum"],
          "ArrayList",
          "unordered_map is HashMap."),
        q("java-list-q4",
          "list.get(list.size()) :",
          ["Returns the last element.", "Throws IndexOutOfBoundsException.",
           "Returns null.", "Appends."],
          "Throws IndexOutOfBoundsException.",
          "Last index is size()-1."),
        q("java-list-q5",
          "Autoboxing in List<Integer>:",
          ["You can store raw int primitives in the list object itself.",
           "add(3) boxes to Integer; be aware of null and extra objects.",
           "List<int> is legal.",
           "Boxing is deprecated."],
          "add(3) boxes to Integer; be aware of null and extra objects.",
          "List<int> is still illegal; arrays of int remain for primitive performance."),
        q("java-list-q6",
          "When is LinkedList reasonable?",
          ["Default for everything.",
           "Heavy insert/remove at ends/middle with little random access — still measure; ArrayDeque often beats it as a queue.",
           "Faster get(i) than ArrayList.",
           "Required for DSA arrays."],
          "Heavy insert/remove at ends/middle with little random access — still measure; ArrayDeque often beats it as a queue.",
          "Interviews: ArrayList unless you know why not."),
        q("java-list-q7",
          "Helsinki ArrayList vs Java array:",
          ["Same type.", "List grows; array length is fixed after creation.",
           "arrays can only hold Strings.", "List cannot hold duplicates, arrays can."],
          "List grows; array length is fixed after creation.",
          "You need both in DSA."),
        q("java-list-q8",
          "Collections Framework intro teaches that you choose a structure based on:",
          ["The first type you memorized.", "Access and usage patterns (lookup vs order vs uniqueness).",
           "The IDE default wizard only.", "Alphabetical order of class names."],
          "Access and usage patterns (lookup vs order vs uniqueness).",
          "This module is the Java side of those choices."),
    ],
    exercises=[
        ex("java-list-ex1", "Choose List on purpose",
           "Build a grocery list: add, remove by index, print, and 'contains'. Use List<String> / ArrayList. "
           "In comments, answer: if you only ever stack push/pop at the end, would ArrayDeque be a better type later? "
           "Do not use LinkedList unless you write a 3-line justification. "
           + DSA_LIST,
           difficulty="intermediate"),
    ],
)

_add(
    "java-set",
    hours=1.0,
    objective="Use HashSet for uniqueness and membership tests.",
    explanation=(
        "Set stores unique elements. HashSet is average O(1) add/contains (C++ unordered_set). "
        "Iteration order is not a contract unless you use LinkedHashSet/TreeSet. "
        "Elements must have consistent equals/hashCode. Helsinki maps uniqueness more via HashMap; Dev.java Set is the reference. "
        + DSA_SET
    ),
    mastery=[
        "Deduplicate a list with a Set and explain equals/hashCode at a high level.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-set-primary", "Set, SortedSet, NavigableSet", DJ_SETS, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative Set tutorial. Helsinki has no dedicated HashSet section in the verified Part 8 map; do not claim one."),
        r("java-set-reference", "Collections Framework intro", DJ_COL_INTRO, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Choosing collections vs arrays and the hierarchy."),
        r("java-set-practice", "Helsinki Part 8 — Hash map", H_P8_MAP, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " Use maps for grouping; separately practice HashSet locally for uniqueness. " + DSA_SET),
    ],
    questions=[
        q("java-set-q1",
          "HashSet.add(x) when x is already present:",
          ["Adds a second copy.", "Leaves uniqueness; add returns false.",
           "Throws.", "Replaces based on insertion index."],
          "Leaves uniqueness; add returns false.",
          "Set is not a bag.",
          mastery=True),
        q("java-set-q2",
          "contains on HashSet is typically used because:",
          ["It is always O(n).", "Average O(1) membership beats scanning a list.",
           "It sorts.", "It requires a Comparator."],
          "Average O(1) membership beats scanning a list.",
          "DSA hashing problems live here."),
        q("java-set-q3",
          "C++ analogue of HashSet:",
          ["vector", "unordered_set", "priority_queue", "string"],
          "unordered_set",
          "std::set is ordered (tree); TreeSet is closer to that."),
        q("java-set-q4",
          "Mutable objects as HashSet elements:",
          ["Fine to change fields that affect hashCode after insert.",
           "Dangerous: changing equals/hashCode fields after insert corrupts the set.",
           "Required.",
           "HashSet copies objects deeply."],
          "Dangerous: changing equals/hashCode fields after insert corrupts the set.",
          "Prefer immutable keys/elements."),
        q("java-set-q5",
          "new HashSet<>(list) is a common way to:",
          ["Sort the list.", "Drop duplicates.",
           "Reverse.", "Index in O(1)."],
          "Drop duplicates.",
          "Order is lost unless LinkedHashSet."),
    ],
    exercises=[
        ex("java-set-ex1", "Unique values",
           "From a List with duplicates, print unique tokens with HashSet and count how many were duplicates. "
           "Implement hasUnseen(Set<Integer> seen, int x) used like a sliding-window helper (language only). "
           + DSA_SET,
           difficulty="intermediate"),
    ],
)

_add(
    "java-map",
    hours=1.5,
    objective="Use HashMap for lookups, frequency, and grouping.",
    explanation=(
        "Map stores key → value. HashMap is average O(1) get/put (C++ unordered_map). Keys need equals/hashCode. "
        "Frequency maps (char → int) and adjacency maps (node → list) are Domain 2 workhorses. "
        "getOrDefault, merge, and iterate entrySet. Null keys: HashMap allows one null key; don't rely on it in DSA. "
        + DSA_MAP
    ),
    mastery=[
        "Implement frequency and lookup with HashMap.",
        "Explain get vs getOrDefault and missing keys.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-map-primary", "Helsinki Part 8 — Hash map", H_P8_MAP, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " HashMap exercises. " + DSA_MAP),
        r("java-map-reference", "Maps", DJ_MAPS, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative Map hierarchy/tutorial."),
        r("java-map-practice", "Helsinki Part 8 — Grouping with hash maps", H_P8_GROUP, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 2,
          HELSINKI_NOTE + " Grouping patterns (Map of lists)."),
    ],
    questions=[
        q("java-map-q1",
          "map.get(missingKey) on HashMap returns:",
          ["0", "throws always", "null", "false"],
          "null",
          "Do not confuse with getOrDefault. Unboxing Integer can NPE.",
          mastery=True),
        q("java-map-q2",
          "Frequency of characters in a string:",
          ["Use Set only.", "Map<Character,Integer> incrementing counts.",
           "Must use TreeMap.", "Requires Streams."],
          "Map<Character,Integer> incrementing counts.",
          "Streams are not a DSA prerequisite."),
        q("java-map-q3",
          "C++ analogue of HashMap:",
          ["map (tree)", "unordered_map", "vector", "deque"],
          "unordered_map",
          "std::map is ordered; TreeMap is closer."),
        q("java-map-q4",
          "Using a mutable key object and then changing it:",
          ["Safe.", "Can lose the entry (hash bucket wrong).",
           "HashMap clones keys.", "Java forbids object keys."],
          "Can lose the entry (hash bucket wrong).",
          "String keys are the usual safe choice."),
        q("java-map-q5",
          "map.put(k,v) when k exists:",
          ["Keeps the old value silently.", "Replaces and returns the previous value.",
           "Throws.", "Adds a second entry with the same key."],
          "Replaces and returns the previous value.",
          "Keys are unique."),
        q("java-map-q6",
          "Adjacency list as Map<Integer, List<Integer>> :",
          ["Illegal.", "A standard graph representation in Java DSA.",
           "Requires inheritance from HashMap.", "Needs virtual threads."],
          "A standard graph representation in Java DSA.",
          "Compose; don't extend HashMap."),
        q("java-map-q7",
          "Why HashMap is not a DSA hashing-theory course:",
          ["It cannot store ints.",
           "You still need to know collisions conceptually, but this topic is the Java API for lookup.",
           "HashMap is O(n) always.",
           "Helsinki forbids HashMap in interviews."],
          "You still need to know collisions conceptually, but this topic is the Java API for lookup.",
          "Domain 2 hashing module goes deeper."),
    ],
    exercises=[
        ex("java-map-ex1", "Frequency, lookup, grouping",
           "1) Frequency map of words in a sentence. 2) Lookup table id → name. 3) Group list of (name, dept) into Map<String, List<String>>. "
           "Print all three. No Stream API required. "
           + DSA_MAP,
           difficulty="intermediate"),
    ],
)

_add(
    "java-iteration",
    hours=0.75,
    objective="Iterate with enhanced for and Iterator; know fail-fast behavior at a high level.",
    explanation=(
        "Enhanced for uses Iterable. Iterator has hasNext/next/remove. "
        "Do not remove from an ArrayList while enhanced-for iterating (ConcurrentModificationException). Use Iterator.remove or iterate indices carefully. "
        "index loops remain valid for arrays and when you need the index."
    ),
    mastery=[
        "Iterate a List two ways and safely remove via Iterator.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-iteration-primary", "Iterating collections", DJ_ITER, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative iteration tutorial."),
        r("java-iteration-practice", "Helsinki Part 3 — Lists", H_P3_LISTS, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " List iteration exercises."),
    ],
    questions=[
        q("java-iteration-q1",
          "for (String s : list) list.remove(s); typically:",
          ["Always works.", "Throws ConcurrentModificationException (fail-fast iterator).",
           "Clears silently.", "Is required."],
          "Throws ConcurrentModificationException (fail-fast iterator).",
          "Use Iterator.remove or removeIf.",
          mastery=True),
        q("java-iteration-q2",
          "Enhanced for on an array:",
          ["Illegal.", "Works; you get elements, not a write-through to the slot if you rebind the loop variable.",
           "Lets you assign to the array slot via the loop variable for primitives.",
           "Requires Iterable on int[]."],
          "Works; you get elements, not a write-through to the slot if you rebind the loop variable.",
          "The loop variable is a copy of the primitive or reference."),
        q("java-iteration-q3",
          "When you need indices:",
          ["You must not use arrays.", "Use a classic for on size()/length.",
           "Iterator always provides the index.", "Use switch."],
          "Use a classic for on size()/length.",
          "Two pointers in DSA need indices."),
        q("java-iteration-q4",
          "iterator.remove():",
          ["Is the supported way to remove during iteration.",
           "Is deprecated.",
           "Only works on maps.",
           "Copies the list first always."],
          "Is the supported way to remove during iteration.",
          "Call next before remove."),
    ],
    exercises=[
        ex("java-iteration-ex1", "Safe remove",
           "Fill an ArrayList with 1..10. Remove evens with Iterator. Then iterate remaining with enhanced for and print. "
           "Deliberately try enhanced-for remove in a throwaway method and comment the exception name."),
    ],
)

_add(
    "java-priority-queue",
    hours=1.0,
    objective="Use PriorityQueue for ordered retrieval and connect it to Comparable/Comparator and heaps.",
    explanation=(
        "PriorityQueue is a heap: poll gives the least element by natural or Comparator order (head is the smallest by default). "
        "It is not a sorted list — only the head is cheap. ArrayDeque is the usual queue/stack (C++ deque). "
        "C++ priority_queue is the analogue of PriorityQueue (and is a max-heap by default — Java's is min-heap by Comparable). "
        + DSA_HEAP
        + " Streams are not required."
    ),
    mastery=[
        "Offer/poll a PriorityQueue and explain min-heap default.",
        "Contrast ArrayDeque vs PriorityQueue vs List.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-priority-queue-primary", "Stacks and queues", DJ_QQ, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Queue hierarchy including deque/stack usage. Combine with PriorityQueue API for heaps."),
        r("java-priority-queue-reference", "PriorityQueue API (Java 21)", PQ_API, "Oracle JDK",
          "REFERENCE", "documentation", 1,
          "Official PriorityQueue specification. Helsinki has no verified dedicated PriorityQueue lesson URL."),
        r("java-priority-queue-deep", "Collections Framework intro", DJ_COL_INTRO, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Choosing structures by access pattern."),
    ],
    questions=[
        q("java-priority-queue-q1",
          "Default PriorityQueue of Integer polls:",
          ["Largest first.", "Smallest first (min-heap / natural order).",
           "Insertion order.", "Random."],
          "Smallest first (min-heap / natural order).",
          "C++ priority_queue defaults to max-heap — a transfer trap.",
          mastery=True),
        q("java-priority-queue-q2",
          "ArrayDeque vs PriorityQueue:",
          ["They are identical.",
           "ArrayDeque is FIFO/LIFO; PriorityQueue retrieves by priority.",
           "ArrayDeque sorts always.",
           "PriorityQueue is a List."],
          "ArrayDeque is FIFO/LIFO; PriorityQueue retrieves by priority.",
          "C++ deque vs priority_queue."),
        q("java-priority-queue-q3",
          "pq.peek() vs poll():",
          ["Both remove.", "peek views the head; poll removes it.",
           "peek throws if empty always the same as get(0).",
           "poll sorts the entire structure into a list."],
          "peek views the head; poll removes it.",
          "Empty: null or throw depending on Queue method (peek vs element)."),
        q("java-priority-queue-q4",
          "Iterating a PriorityQueue with enhanced for:",
          ["Visits elements in sorted order always.",
           "Does not guarantee sorted order; only poll order is the heap order.",
           "Is illegal.",
           "Reverses the heap."],
          "Does not guarantee sorted order; only poll order is the heap order.",
          "Don't print-for-each and assume sorted."),
        q("java-priority-queue-q5",
          "This topic is a heap DSA prerequisite because:",
          ["PriorityQueue is the usual Java heap.",
           "You must implement binary heap from scratch first.",
           "Graphs require PriorityQueue only.",
           "Streams replace heaps."],
          "PriorityQueue is the usual Java heap.",
          "Domain 2 still teaches heap operations conceptually."),
        q("java-priority-queue-q6",
          "Need a max-heap of ints:",
          ["Impossible.", "Comparator.reverseOrder() or store negatives if you know what you are doing.",
           "Use HashSet.", "Use StringBuilder."],
          "Comparator.reverseOrder() or store negatives if you know what you are doing.",
          "Next topic is Comparable/Comparator."),
    ],
    exercises=[
        ex("java-priority-queue-ex1", "Queue vs heap vs deque",
           "1) ArrayDeque as queue: offer 1,2,3 poll all. 2) ArrayDeque as stack: push/pop. 3) PriorityQueue of 5,1,4 poll all and record order. "
           "4) One sentence C++ mapping: vector/ArrayList already done; deque/ArrayDeque; priority_queue/PriorityQueue. "
           + DSA_HEAP,
           difficulty="intermediate"),
    ],
)

_add(
    "java-generic-types",
    hours=1.0,
    objective="Declare generic classes and methods for type-safe containers.",
    explanation=(
        "Generics parameterize types: Box<T>, List<String>. They exist for compile-time type safety. "
        "At runtime, type erasure means the JVM sees raw types (conceptual level only). "
        "Do not overteach PECS yet — next topic. Helsinki Part 12 type parameters is the exercise layer."
    ),
    mastery=[
        "Write a generic Box<T> and a generic utility method.",
        "Explain type safety vs erasure at a high level.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-generic-types-primary", "Helsinki Part 12 — Type parameters", H_P12_GEN, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Generic type exercises."),
        r("java-generic-types-reference", "Generics intro", DJ_GEN, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Authoritative generics introduction."),
        r("java-generic-types-deep", "Type erasure", DJ_ERASE, "Dev.java",
          "DEEP_DIVE", "documentation", 2,
          "Conceptual erasure only — not a type-theory course."),
    ],
    questions=[
        q("java-generic-types-q1",
          "Box<String> vs Box without type:",
          ["Raw Box is just as safe.",
           "Box<String> lets the compiler reject Box.set(1).",
           "Generics run faster always.",
           "String is a primitive."],
          "Box<String> lets the compiler reject Box.set(1).",
          "Raw types exist for history; don't use them in new code.",
          mastery=True),
        q("java-generic-types-q2",
          "Type erasure means:",
          ["The compiler deletes your classes.",
           "Most generic type arguments are not available as runtime T.class in the usual way; checks are compile-time.",
           "ArrayList<String> cannot hold strings at runtime.",
           "You cannot write Box<T>."],
          "Most generic type arguments are not available as runtime T.class in the usual way; checks are compile-time.",
          "Enough for interviews: don't write new T[]."),
        q("java-generic-types-q3",
          "static <T> T first(List<T> xs):",
          ["Illegal static generic.", "A generic method; T is inferred from the argument.",
           "T must be String.", "Erasure forbids this."],
          "A generic method; T is inferred from the argument.",
          "Utility methods are often generic."),
        q("java-generic-types-q4",
          "ArrayList<int>:",
          ["Legal in all JDKs.", "Illegal; use ArrayList<Integer> or int[].",
           "Faster than int[].", "Required for DSA."],
          "Illegal; use ArrayList<Integer> or int[].",
          "Primitives vs wrappers again."),
        q("java-generic-types-q5",
          "A generic linked-list node Node<T> is useful later because:",
          ["Trees cannot store T.", "The same pointer structure can hold any payload type with type safety.",
           "T replaces references.", "It avoids null."],
          "The same pointer structure can hold any payload type with type safety.",
          "Still pass-by-value of references."),
    ],
    exercises=[
        ex("java-generic-types-ex1", "Box and first()",
           "Implement Box<T> with get/set. Implement static <T> T firstNonNull(T a, T b). "
           "Use Box<Integer> and Box<String>. Comment one sentence on erasure. "
           + HELSINKI_NOTE),
    ],
)

_add(
    "java-generic-bounds",
    hours=0.75,
    objective="Read simple upper bounds and wildcards without becoming a generics lawyer.",
    explanation=(
        "T extends Number restricts T. Wildcards: List<?> unknown, List<? extends Number> producer, List<? super Integer> consumer (PECS at slogan level). "
        "You need to read these in APIs. You do not need to invent nested wildcards for DSA."
    ),
    mastery=[
        "Write a bounded method (T extends Comparable<T> or Number).",
        "Explain ? extends vs a concrete type in one example.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-generic-bounds-primary", "Wildcards", DJ_WILD, "Dev.java",
          "PRIMARY", "documentation", 0,
          "Authoritative wildcards. Helsinki Part 12 covers type parameters more than wildcard theory."),
        r("java-generic-bounds-practice", "Helsinki Part 12 — Type parameters", H_P12_GEN, "University of Helsinki",
          "PRACTICE", "interactive_tutorial", 1,
          HELSINKI_NOTE + " Stay on simple type parameters if wildcards are thin; implement a bounded method locally."),
    ],
    questions=[
        q("java-generic-bounds-q1",
          "<T extends Number> double sum(List<T> xs) can take:",
          ["List<String>", "List<Integer>", "List<Object> always", "int[] only"],
          "List<Integer>",
          "Integer extends Number.",
          mastery=True),
        q("java-generic-bounds-q2",
          "List<? extends Number> is a producer: you typically:",
          ["add arbitrary Number instances freely.", "get Numbers (read) but cannot add except null.",
           "must be List<Number> exactly.", "erases to List<String>."],
          "get Numbers (read) but cannot add except null.",
          "PECS: producer extends."),
        q("java-generic-bounds-q3",
          "Why DSA does not require expert wildcards:",
          ["DSA never uses lists.",
           "ArrayList<Integer> and HashMap<K,V> cover almost all solutions.",
           "Wildcards are illegal in interviews.",
           "PriorityQueue cannot be generic."],
          "ArrayList<Integer> and HashMap<K,V> cover almost all solutions.",
          "Read APIs; don't design wildcard towers."),
        q("java-generic-bounds-q4",
          "Comparable bound shows up because:",
          ["sort/heap need a comparison protocol.",
           "Number is Comparable always in a useful way for all subclasses together.",
           "Wildcards replace Comparator.",
           "Erasure sorts for you."],
          "sort/heap need a comparison protocol.",
          "Next module."),
    ],
    exercises=[
        ex("java-generic-bounds-ex1", "Bounded copy",
           "Write <T extends Number> double sum(List<T> nums). Call with List<Integer> and List<Double>. "
           "Attempt sum(List<String>) and record the compile error. Optional: void addNumbers(List<? super Integer> sink)."),
    ],
)

_add(
    "java-comparable-comparator",
    hours=1.25,
    objective="Order objects with Comparable and Comparator, including multi-field and lambda comparators.",
    explanation=(
        "Comparable.compareTo is the type's natural order. Comparator is an external strategy (multiple criteria, reverse). "
        "Collections.sort / List.sort / PriorityQueue use these. "
        "Lambda: Comparator.comparing(Person::age).thenComparing(Person::name). "
        + DSA_HEAP
    ),
    mastery=[
        "Sort domain objects by natural order and by a second Comparator.",
        "Use a Comparator with PriorityQueue.",
        "Score >= 80% on the topic questions.",
    ],
    resources=[
        r("java-comparable-comparator-primary", "Helsinki Part 10 — Comparable", H_P10_COMP, "University of Helsinki",
          "PRIMARY", "interactive_tutorial", 0,
          HELSINKI_NOTE + " Comparable exercises. " + DSA_HEAP),
        r("java-comparable-comparator-reference", "Writing comparators (lambdas)", DJ_COMP_LAM, "Dev.java",
          "REFERENCE", "documentation", 1,
          "Modern Comparator construction. Lambdas here support sorting; lambda module is still not a DSA gate."),
        r("java-comparable-comparator-deep", "Comparable API (Java 21)", CMP_API, "Oracle JDK",
          "DEEP_DIVE", "documentation", 2,
          "Official compareTo contract (sgn, consistency with equals — know it exists)."),
    ],
    questions=[
        q("java-comparable-comparator-q1",
          "compareTo returning negative means:",
          ["this is greater.", "this is less than the other (this comes first in ascending sort).",
           "equal.", "error."],
          "this is less than the other (this comes first in ascending sort).",
          "sgn(this - other) for numbers with overflow caveats — prefer Integer.compare.",
          mastery=True),
        q("java-comparable-comparator-q2",
          "Comparator vs Comparable:",
          ["Comparator is the only legal way to sort Strings.",
           "Comparable is on the class; Comparator is a separate object for alternate orders.",
           "They cannot be used with PriorityQueue.",
           "Comparator requires Spring."],
          "Comparable is on the class; Comparator is a separate object for alternate orders.",
          "String is Comparable; you still might want length Comparator."),
        q("java-comparable-comparator-q3",
          "Multi-field: sort by last name then first:",
          ["Impossible.", "thenComparing chained Comparators (or compare last, then first in compareTo).",
           "Two separate sorts always required.", "Must use Streams."],
          "thenComparing chained Comparators (or compare last, then first in compareTo).",
          "Stable sort preserves equal keys."),
        q("java-comparable-comparator-q4",
          "PriorityQueue(Comparator.reverseOrder()) for Integer:",
          ["Min-heap.", "Max-heap (largest polls first).",
           "Insertion order.", "Deduplicates."],
          "Max-heap (largest polls first).",
          "Heap DSA module depends on this."),
        q("java-comparable-comparator-q5",
          "Inconsistent compareTo vs equals:",
          ["Fine always.", "Can break sorted sets/maps that assume consistency; know the risk.",
           "Required for HashMap.", "Makes HashSet faster."],
          "Can break sorted sets/maps that assume consistency; know the risk.",
          "Read the Comparable contract when you implement it."),
        q("java-comparable-comparator-q6",
          "Lambdas for Comparator are:",
          ["A DSA prerequisite for arrays.",
           "Convenient syntax; you could still write an anonymous class.",
           "Required before HashMap.",
           "Illegal on PriorityQueue."],
          "Convenient syntax; you could still write an anonymous class.",
          "Don't block DSA on the lambdas module."),
    ],
    exercises=[
        ex("java-comparable-comparator-ex1", "Sort people and a heap",
           "Person(name, age). Natural order by name (Comparable). Comparator by age, then name. Sort a list both ways. "
           "PriorityQueue<Person> youngest-first. Reverse age comparator for oldest-first. "
           + DSA_HEAP,
           difficulty="intermediate"),
    ],
)
