"""Official V1 Java and DSA module/topic specs. No URLs, questions, or exercises."""

from __future__ import annotations


def C(*skills: str) -> list[str]:
    return list(skills)


def D(*skills: str) -> list[str]:
    items = list(skills)
    for extra in (
        "Explain the idea without notes (language-independent).",
        "Implement in Java without copying.",
        "State the C++ equivalent at a high level if you already know it.",
        "Solve 2 representative problems independently.",
        "State time and space complexity of a correct approach.",
        "Name one common mistake for this topic.",
        "Score >= 80%.",
    ):
        if extra not in items:
            items.append(extra)
    return items


def java_spec() -> list[tuple]:
    return [
        ("java-getting-started", "Getting Started", [
            ("java-jdk-jre", "JDK and JRE", "Install and explain JDK vs JRE.",
             C("Explain JDK vs JRE without notes.", "Compile and run a class from the toolchain you will use.", "Score >= 80%."),
             "What you install to write and run Java."),
            ("java-first-program", "First program", "Write, compile, and run Hello World.",
             C("Produce a running Hello World independently.", "Score >= 80%."),
             "main method and a single class."),
            ("java-compile-and-run", "Compile and run", "Use javac/java or the IDE equivalent reliably.",
             C("Explain .java vs .class.", "Score >= 80%."),
             "The compile-run loop. Tooling for the rest of Java and DSA."),
        ]),
        ("java-variables-types", "Variables & Types", [
            ("java-primitives", "Primitives", "Use Java primitive types correctly.",
             C("List the primitive types.", "Choose types for simple data.", "Score >= 80%."),
             "byte through boolean, including int and double."),
            ("java-type-conversion", "Type conversion", "Apply widening and narrowing conversions.",
             C("Show a safe widening and an explicit cast.", "Score >= 80%."),
             "Casts and overflow at a basic level."),
        ]),
        ("java-input-output", "Input & Output", [
            ("java-console-io", "Console input and output", "Read input and print output from a console program.",
             C("Write a program that reads values and prints a result independently.", "Score >= 80%."),
             "System.out and a simple input API. File I/O comes later."),
        ]),
        ("java-operators", "Operators", [
            ("java-operators", "Operators", "Use arithmetic, comparison, and boolean operators.",
             C("Evaluate a mixed expression with precedence.", "Score >= 80%."),
             "Expressions and assignment."),
        ]),
        ("java-control-flow", "Control Flow", [
            ("java-if-else", "if/else", "Branch with if/else.",
             C("Write nested conditions for a small spec.", "Score >= 80%."),
             "Boolean control."),
            ("java-switch", "switch", "Use switch for multi-way branching.",
             C("Rewrite a simple if-chain as switch.", "Score >= 80%."),
             "Classic switch. Pattern matching is later/reference, not a DSA gate."),
            ("java-loops", "Loops", "Use for, while, and do-while appropriately.",
             C("Implement a counted loop and a sentinel loop.", "Score >= 80%."),
             "Iteration."),
            ("java-break-continue", "break and continue", "Control loop flow deliberately.",
             C("Explain break vs continue with an example.", "Score >= 80%."),
             "Early exit and skip."),
        ]),
        ("java-methods", "Methods", [
            ("java-method-basics", "Method basics", "Declare methods with parameters and return values.",
             C("Implement a small pure method independently.", "Score >= 80%."),
             "Signatures and calls. Enough Java to start language-independent DSA thinking."),
            ("java-overloading", "Overloading", "Overload methods by parameter lists.",
             C("Write two overloads and explain resolution at a high level.", "Score >= 80%."),
             "Same name, different parameters."),
            ("java-scope", "Scope", "Reason about local vs class-level variables.",
             C("Identify the scope of a variable in a short snippet.", "Score >= 80%."),
             "Lifetime and visibility of names."),
        ]),
        ("java-arrays", "Arrays", [
            ("java-arrays", "Arrays", "Allocate, index, and iterate arrays.",
             C("Implement a linear scan on an int array without copying.", "Score >= 80%."),
             "Fixed-length arrays. Minimum Java for array DSA."),
        ]),
        ("java-strings", "Strings", [
            ("java-strings", "Strings", "Use String immutability and common operations.",
             C("Explain why String is immutable.", "Solve a simple string task independently.", "Score >= 80%."),
             "java.lang.String. Minimum Java for string DSA."),
            ("java-stringbuilder", "StringBuilder", "Build strings efficiently.",
             C("State when StringBuilder is preferred.", "Score >= 80%."),
             "Mutable character sequences."),
        ]),
        ("java-oop", "Object-Oriented Programming", [
            ("java-classes-objects", "Classes and objects", "Define a class and construct objects.",
             C("Implement a small class with state and behavior.", "Score >= 80%."),
             "Objects as bundled data and methods. Minimum Java for node-based DSA."),
            ("java-references", "References", "Explain reference vs primitive semantics.",
             C("Trace aliasing of two variables pointing at one object.", "Score >= 80%."),
             "Why linked structures and graphs share nodes. Minimum Java for lists/trees/graphs."),
            ("java-constructors", "Constructors", "Write constructors and overloaded constructors.",
             C("Initialize all fields via constructors.", "Score >= 80%."),
             "Creation of valid objects."),
            ("java-encapsulation", "Encapsulation", "Use private fields and accessors appropriately.",
             C("Explain why fields are typically private.", "Score >= 80%."),
             "Protecting invariants."),
            ("java-inheritance", "Inheritance", "Extend a class and use super.",
             C("Draw a two-level hierarchy for a simple domain.", "Score >= 80%."),
             "is-a relationships. Avoid deep hierarchies."),
            ("java-polymorphism", "Polymorphism", "Call overridden methods through a supertype.",
             C("Explain dynamic dispatch with one example.", "Score >= 80%."),
             "Same message, different implementations."),
        ]),
        ("java-interfaces-abstraction", "Interfaces & Abstraction", [
            ("java-abstract-classes", "Abstract classes", "Declare abstract methods and classes.",
             C("Contrast abstract class vs concrete class.", "Score >= 80%."),
             "Partial implementation."),
            ("java-interfaces", "Interfaces", "Implement an interface.",
             C("Write an interface and two implementations.", "Score >= 80%."),
             "Contracts without implementation (default methods mentioned, not required)."),
            ("java-composition", "Composition", "Prefer composition for has-a relationships.",
             C("Refactor a forced inheritance example to composition on paper.", "Score >= 80%."),
             "Delegation instead of inheritance when appropriate."),
        ]),
        ("java-exceptions", "Exceptions", [
            ("java-try-catch", "try/catch", "Handle exceptions locally when you can recover.",
             C("Write try/catch/finally for a simple failure.", "Score >= 80%."),
             "Control flow for failures."),
            ("java-checked-unchecked", "Checked and unchecked", "Explain the two families.",
             C("Classify RuntimeException vs IOException conceptually.", "Score >= 80%."),
             "Compiler-enforced vs not."),
            ("java-custom-exceptions", "Custom exceptions", "Define a simple domain exception.",
             C("Create and throw a custom unchecked exception.", "Score >= 80%."),
             "When built-in types are not enough."),
        ]),
        ("java-collections", "Collections", [
            ("java-list", "List", "Use List and ArrayList.",
             C("Choose List vs array for a growing sequence.", "Implement a small List-based task.", "Score >= 80%."),
             "Ordered collections. Used by stacks/queues/graphs."),
            ("java-set", "Set", "Use HashSet for uniqueness.",
             C("Explain why Set does not allow duplicates.", "Score >= 80%."),
             "Membership. Minimum Java for hash-set DSA."),
            ("java-map", "Map", "Use HashMap for key-value data.",
             C("Implement a frequency count with Map.", "Score >= 80%."),
             "Associative arrays. Minimum Java for hashing DSA."),
            ("java-iteration", "Iteration", "Iterate with for-each and iterators.",
             C("Traverse a collection without index bugs.", "Score >= 80%."),
             "Walking collections."),
            ("java-priority-queue", "PriorityQueue", "Use PriorityQueue for ordered retrieval.",
             C("Explain poll vs peek.", "Score >= 80%."),
             "Minimum Java for heap DSA. Comparator details in the next module."),
        ]),
        ("java-generics", "Generics", [
            ("java-generic-types", "Generic types", "Declare and use a generic type parameter.",
             C("Write List<String> usage without raw types.", "Score >= 80%."),
             "Type parameters on classes and methods."),
            ("java-generic-bounds", "Bounds", "Read a simple upper bound.",
             C("Explain <T extends Number> in one sentence.", "Score >= 80%."),
             "Constrained type parameters. Wildcards optional in V1."),
        ]),
        ("java-comparable-comparator", "Comparable & Comparator", [
            ("java-comparable-comparator", "Comparable and Comparator", "Order objects with Comparable or Comparator.",
             C("Sort a list of objects with a Comparator.", "Score >= 80%."),
             "Natural order vs explicit ordering. Supports heaps and library sort."),
        ]),
        ("java-lambdas", "Lambdas & Functional Programming", [
            ("java-functional-interfaces", "Functional interfaces", "Identify a single-abstract-method interface.",
             C("Name Predicate or Function as an example.", "Score >= 80%."),
             "The target type for lambdas. Not a DSA prerequisite."),
            ("java-lambdas", "Lambdas", "Write a lambda or method reference for a simple callback.",
             C("Replace a one-method anonymous class with a lambda.", "Score >= 80%."),
             "Concise implementation of functional interfaces. Not a DSA prerequisite."),
        ]),
        ("java-streams", "Streams", [
            ("java-stream-pipeline", "Stream pipeline", "Build map/filter/collect pipelines.",
             C("Write a filter+map+collect independently.", "Score >= 80%."),
             "Lazy sequences over collections. Not a DSA prerequisite."),
            ("java-stream-operations", "Common operations", "Use map, filter, reduce/collect.",
             C("Choose filter vs map for a given transform.", "Score >= 80%."),
             "The everyday stream toolbox. Parallel streams not required."),
        ]),
        ("java-file-io", "File I/O", [
            ("java-paths-files", "Paths and files", "Use Path and Files for simple checks.",
             C("Check that a file exists using NIO.2.", "Score >= 80%."),
             "java.nio.file basics. Not a DSA prerequisite."),
            ("java-readers-writers", "Readers and writers", "Read and write text files.",
             C("Read a small text file and write a result file independently.", "Score >= 80%."),
             "Character streams. Binary I/O optional."),
        ]),
        ("java-testing", "Testing", [
            ("java-junit-basics", "JUnit basics", "Run a unit test with JUnit.",
             C("Write a failing test then make it pass.", "Score >= 80%."),
             "JUnit 5 as the V1 default. Not a DSA prerequisite."),
            ("java-assertions", "Assertions", "Use assertions for return values and exceptions.",
             C("Assert equals and thrown exception.", "Score >= 80%."),
             "What to verify."),
        ]),
        ("java-concurrency", "Concurrency Basics", [
            ("java-threads", "Threads", "Start a Thread or use a simple executor conceptually.",
             C("Explain why shared mutable state is dangerous.", "Score >= 80%."),
             "Multiple call stacks. Not a DSA prerequisite. Virtual threads are later/reference."),
            ("java-synchronization-basics", "Synchronization basics", "Explain synchronized at a high level.",
             C("State one correctness bug from missing synchronization.", "Score >= 80%."),
             "Mutual exclusion idea. Advanced concurrency deferred."),
        ]),
        ("java-jvm", "JVM Fundamentals", [
            ("java-bytecode", "Bytecode", "Explain class files as JVM bytecode.",
             C("Contrast javac output with CPU machine code.", "Score >= 80%."),
             "Portable instructions for the JVM. Not a DSA prerequisite."),
            ("java-memory-model-basics", "Memory model basics", "Name heap vs stack at a Java programmer level.",
             C("Place objects vs local primitives.", "Score >= 80%."),
             "Where data lives. Formal JMM deferred."),
            ("java-gc-intro", "Garbage collection intro", "Explain reachability and GC at a high level.",
             C("Explain why Java has no free().", "Score >= 80%."),
             "Automatic memory management. Collector algorithms deferred."),
        ]),
        ("java-practices", "Java Development Practices", [
            ("java-packages", "Packages", "Organize classes into packages.",
             C("Create two packages and an import.", "Score >= 80%."),
             "Namespaces. Not a DSA prerequisite."),
            ("java-api-hygiene", "API hygiene", "Name methods clearly and keep methods small.",
             C("Refactor a bloated method on paper.", "Score >= 80%."),
             "Readability as a professional habit. Records/modules/pattern matching are later/reference."),
        ]),
    ]


def dsa_spec() -> list[tuple]:
    ja = ["java-arrays"]
    js = ["java-strings"]
    jh = ["java-map", "java-set"]
    jref = ["java-classes-objects", "java-references"]
    jcol = ["java-list"]
    jheap = ["java-priority-queue", "java-comparable-comparator"]
    jgraph = ["java-list", "java-map", "java-classes-objects", "java-references"]
    jm = ["java-method-basics"]

    return [
        ("dsa-algorithmic-thinking", "Algorithmic Thinking", [
            ("dsa-algorithmic-thinking", "Algorithmic thinking",
             "Approach problems with input/output, invariants, and examples.",
             D("Write input/output and two examples before coding."),
             "Language-independent problem setup. C++ experience transfers; Java is the primary implementation language."),
        ], jm),
        ("dsa-complexity", "Complexity Analysis", [
            ("dsa-big-o", "Big-O notation",
             "Read and write simple big-O for loops.",
             D("Give big-O for nested loops of n."),
             "Formalizes the Domain 0 intro. Independent of Java vs C++."),
            ("dsa-best-worst-average", "Best, worst, average",
             "Distinguish those cases.",
             D("Give an example where best and worst differ."),
             "Why worst-case is the usual interview default."),
        ]),
        ("dsa-arrays", "Arrays", [
            ("dsa-array-traversal", "Array traversal",
             "Scan an array in linear time.",
             D("Implement a traversal in Java without copying."),
             "Indexing, bounds, left-to-right and reverse scans."),
            ("dsa-array-insert-delete", "Insertion and deletion concepts",
             "Explain insert/delete cost in a contiguous array.",
             D("State shifting cost for insert at index i."),
             "Why ArrayList amortized append differs from middle insert."),
            ("dsa-prefix-sums", "Prefix sums",
             "Build and query a prefix array.",
             D("Answer a range-sum with prefixes."),
             "Precomputation for range queries."),
            ("dsa-array-frequency", "Frequency counting",
             "Count values with an array or map as appropriate.",
             D("Build a frequency table for a bounded alphabet."),
             "Counting before hashing as a first tool."),
            ("dsa-array-patterns", "Array patterns",
             "Recognize in-place scans and two-index setups at a basic level.",
             D("Name two array patterns and when to use them."),
             "Bridge into two pointers and windows."),
        ], ja),
        ("dsa-strings", "Strings", [
            ("dsa-string-manipulation", "String manipulation",
             "Transform strings with clear index logic.",
             D("Implement a reverse or substring-style task in Java."),
             "Strings as sequences of characters."),
            ("dsa-string-frequency", "String frequency",
             "Count characters or tokens.",
             D("Build a character frequency table."),
             "Anagrams and counting."),
            ("dsa-character-processing", "Character processing",
             "Classify and map characters.",
             D("Use char arithmetic or APIs for a simple transform."),
             "Digits, case, and ASCII/Unicode at V1 depth."),
            ("dsa-string-patterns", "String patterns",
             "Apply common string interview patterns.",
             D("Classify a string prompt into a known pattern."),
             "Treat strings as array problems plus immutability."),
        ], js),
        ("dsa-hashing", "Hashing", [
            ("dsa-hash-map", "Hash map",
             "Use hash maps for expected O(1) keyed lookup.",
             D("Explain collision at a high level."),
             "Java HashMap; C++ unordered_map as the equivalent."),
            ("dsa-hash-set", "Hash set",
             "Use hash sets for membership.",
             D("Choose set vs map for a membership task."),
             "Java HashSet; C++ unordered_set as the equivalent."),
            ("dsa-frequency-maps", "Frequency maps",
             "Count with a map when the alphabet is large.",
             D("Implement a frequency map in Java."),
             "When an array of counts is not enough."),
            ("dsa-lookup-patterns", "Lookup patterns",
             "Apply two-sum / seen-set style lookups.",
             D("Dry-run a one-pass lookup pattern."),
             "Hashing as an algorithmic tool, not a Java trivia topic."),
        ], jh),
        ("dsa-two-pointers", "Two Pointers", [
            ("dsa-two-pointers-opposite", "Opposite-direction pointers",
             "Move pointers from both ends.",
             D("Dry-run opposite pointers on a sorted array."),
             "Pair sums and partitioning from the ends."),
            ("dsa-two-pointers-same", "Same-direction pointers",
             "Advance read/write or slow/fast indexes in one direction.",
             D("Dry-run an in-place compacting scan."),
             "Removing duplicates and similar linear passes."),
            ("dsa-two-pointers-partition", "Partition-style patterns",
             "Partition an array around a condition.",
             D("Explain a Dutch-national-flag or pivot partition at a high level."),
             "Hoare/Lomuto intuition without requiring full quicksort yet."),
        ], ja),
        ("dsa-sliding-window", "Sliding Window", [
            ("dsa-window-fixed", "Fixed window",
             "Maintain a window of fixed length.",
             D("Compute a fixed-window aggregate in linear time."),
             "Add entering element, drop leaving element."),
            ("dsa-window-variable", "Variable window",
             "Grow and shrink a window to meet a constraint.",
             D("Explain why the window moves, not restarts."),
             "Two pointers as a window."),
            ("dsa-window-frequency", "Frequency window state",
             "Track counts or distinct values inside a window.",
             D("Update a frequency map as the window moves."),
             "Needs hashing for general alphabets."),
        ], ja + ["java-map"]),
        ("dsa-linked-lists", "Linked Lists", [
            ("dsa-singly-linked-list", "Singly linked list",
             "Represent a node-based list.",
             D("Draw nodes and next references."),
             "Java references vs C++ pointers: same structure, different syntax."),
            ("dsa-list-operations", "List operations",
             "Insert, delete, and find by walking next.",
             D("Implement insert/delete on a singly linked list in Java."),
             "Dummy heads when they simplify edge cases."),
            ("dsa-list-reversal", "Reversal",
             "Reverse a singly linked list iteratively.",
             D("Reverse a list without copying."),
             "Three-pointer reverse."),
            ("dsa-fast-slow", "Fast and slow pointers",
             "Use two speeds on a list.",
             D("Find the middle node with fast/slow."),
             "Same idea as cycle detection setup."),
            ("dsa-cycle-detection", "Cycle detection",
             "Detect a cycle in a linked list.",
             D("Explain why fast/slow meets in a cycle."),
             "Floyd's method at V1 depth."),
            ("dsa-list-merge", "Merge patterns",
             "Merge two sorted lists or split/merge.",
             D("Merge two sorted lists."),
             "Foundation for merge sort on lists."),
        ], jref),
        ("dsa-stack", "Stack", [
            ("dsa-stack-fundamentals", "Stack fundamentals",
             "Use LIFO for matching and nested structure.",
             D("Implement stack operations; solve matching-brackets style work."),
             "Java Deque/Stack usage; C++ std::stack as equivalent."),
            ("dsa-monotonic-stack", "Monotonic stack",
             "Maintain an increasing or decreasing stack.",
             D("Dry-run next-greater-element with a monotonic stack."),
             "A pattern, not a new data structure."),
        ], jref + jcol),
        ("dsa-queue", "Queue", [
            ("dsa-queue-deque", "Queue and deque",
             "Use FIFO and double-ended queues.",
             D("Implement BFS-ready queue usage in Java."),
             "Java Queue/Deque; C++ std::queue / deque as equivalent."),
            ("dsa-queue-bfs-relationship", "BFS relationship",
             "Explain why BFS uses a queue.",
             D("Contrast stack-DFS vs queue-BFS at a high level."),
             "Prepares graph BFS. Full graph traversal comes later."),
        ], jref + jcol),
        ("dsa-recursion", "Recursion", [
            ("dsa-recursion-model", "Recursion model",
             "Write recursive functions with a clear base case.",
             D("Implement a simple recursive function without copying."),
             "Base case, recursive case. Language-independent."),
            ("dsa-call-stack", "Call stack",
             "Trace frames on the call stack.",
             D("Trace recursion on paper for a small input."),
             "Why deep recursion fails. Relates to Domain 0 stack memory."),
            ("dsa-recursive-trees", "Recursive tree problems",
             "Recurse on a branching structure.",
             D("Draw the recursion tree for a tiny input."),
             "Preview of trees and backtracking."),
            ("dsa-recursion-to-iteration", "Recursion to iteration",
             "Rewrite a simple recursion as a loop or explicit stack.",
             D("Convert a tail-style recursion to iteration."),
             "When the call stack is just a stack."),
        ], jm),
        ("dsa-backtracking", "Backtracking", [
            ("dsa-subsets", "Subsets",
             "Generate subsets by choose/skip.",
             D("Dry-run subset recursion on a 3-element set."),
             "Include/exclude pattern."),
            ("dsa-permutations", "Permutations",
             "Generate permutations by swapping or used-flags.",
             D("Dry-run permutation search on 3 items."),
             "Ordering of choices."),
            ("dsa-combinations", "Combinations",
             "Generate combinations with an index cursor.",
             D("Contrast combinations vs permutations."),
             "Choose k from n."),
            ("dsa-constraint-search", "Constraint search",
             "Prune when a partial assignment cannot work.",
             D("State one prune condition for a tiny puzzle."),
             "Backtracking as search with undo. No solver libraries."),
        ]),
        ("dsa-sorting", "Sorting", [
            ("dsa-bubble-sort", "Bubble sort",
             "Explain bubble sort and its cost.",
             D("Dry-run bubble sort on 5 elements."),
             "Teaching sort, not a production default."),
            ("dsa-selection-sort", "Selection sort",
             "Explain selection sort and its cost.",
             D("Dry-run selection sort on 5 elements."),
             "Repeated minimum selection."),
            ("dsa-insertion-sort", "Insertion sort",
             "Explain insertion sort and when it is useful.",
             D("Dry-run insertion sort on 5 elements."),
             "Good on nearly sorted input."),
            ("dsa-merge-sort", "Merge sort",
             "Explain divide-and-conquer merge sort.",
             D("Trace merge on two sorted runs."),
             "Stable n log n. Implementation in Java without copying."),
            ("dsa-quick-sort", "Quick sort",
             "Explain quicksort and pivot partitioning.",
             D("Trace one partition step."),
             "Average n log n; worst-case awareness."),
            ("dsa-heap-sort", "Heap sort",
             "Explain heapsort at a conceptual level.",
             D("Relate heapsort to the heap structure."),
             "Full heap operations are deepened in the heap module."),
            ("dsa-counting-radix", "Counting and radix concepts",
             "Explain non-comparison sorts at V1 depth.",
             D("State when counting sort applies."),
             "Not a default interview implementation unless asked."),
            ("dsa-sort-stability", "Stability",
             "Define stable sorting.",
             D("Give one case where stability matters."),
             "Why merge sort is often preferred when equal keys must keep order."),
            ("dsa-sort-complexity", "Complexity comparison",
             "Compare common sorts by time, space, and stability.",
             D("Fill a comparison table from memory."),
             "Prefer library sort in production Java and C++."),
        ], ja),
        ("dsa-binary-search", "Binary Search", [
            ("dsa-binary-search-classic", "Classic search",
             "Search a sorted array.",
             D("Implement binary search in Java without copying."),
             "Midpoint, discard half."),
            ("dsa-binary-search-boundaries", "Boundaries",
             "Get low/high updates right.",
             D("Explain an off-by-one binary-search bug."),
             "Inclusive vs exclusive bounds."),
            ("dsa-first-last-occurrence", "First and last occurrence",
             "Find leftmost or rightmost match.",
             D("Adjust classic search for first occurrence."),
             "Lower/upper bound."),
            ("dsa-search-on-answer", "Search on the answer",
             "Binary search a monotonic predicate.",
             D("State a monotonic predicate for a minimization prompt."),
             "The answer lives in a numeric range."),
            ("dsa-rotated-arrays", "Rotated arrays",
             "Search in a rotated sorted array.",
             D("Identify which half is sorted."),
             "A standard interview variant."),
        ], ja),
        ("dsa-trees", "Trees", [
            ("dsa-tree-terminology", "Tree terminology",
             "Use root, child, parent, leaf, depth, height correctly.",
             D("Define those terms without notes."),
             "Vocabulary before code."),
            ("dsa-binary-trees", "Binary trees",
             "Represent a binary tree node.",
             D("Implement a tree node in Java."),
             "Left/right references. Same as C++ left/right pointers."),
            ("dsa-tree-dfs", "DFS traversals",
             "Perform preorder, inorder, and postorder.",
             D("Dry-run three DFS orders on a 3-node tree."),
             "Recursion on children."),
            ("dsa-tree-bfs", "BFS / level order",
             "Traverse level by level.",
             D("Implement level order with a queue."),
             "Connects to the queue module."),
            ("dsa-tree-height", "Height and depth",
             "Compute height/depth recursively.",
             D("Compute height of a small tree."),
             "Balanced vs skewed awareness, no AVL yet."),
            ("dsa-tree-paths", "Path problems",
             "Accumulate values along root-to-leaf or node-to-node paths.",
             D("Dry-run a path-sum on a tiny tree."),
             "Backtracking on trees."),
            ("dsa-tree-construction", "Construction",
             "Rebuild a tree from traversals at V1 depth.",
             D("Explain why inorder+preorder can reconstruct a binary tree."),
             "Interview construction prompts, not all encodings."),
        ], jref),
        ("dsa-bst", "Binary Search Trees", [
            ("dsa-bst-search", "BST search",
             "Search using BST ordering.",
             D("Trace search in a small BST."),
             "Left < node < right as the V1 convention."),
            ("dsa-bst-insert", "BST insertion",
             "Insert while preserving BST order.",
             D("Insert a key and draw the result."),
             "Implementation in Java without copying."),
            ("dsa-bst-delete", "BST deletion",
             "Delete a node including the two-child case conceptually.",
             D("Explain successor-based delete."),
             "Full production delete is enough at explanation+basic code."),
            ("dsa-bst-validate", "BST validation",
             "Check the BST property with bounds.",
             D("Explain why a local left<parent<right check is insufficient."),
             "Range validation."),
            ("dsa-bst-ordered-properties", "Ordered properties",
             "Use inorder of a BST as a sorted sequence.",
             D("State kth-smallest via inorder."),
             "Why inorder is special. Balancing deferred."),
        ], jref),
        ("dsa-heaps", "Heaps & Priority Queues", [
            ("dsa-heap-structure", "Heap structure",
             "Explain a binary heap as a complete tree.",
             D("Map a heap to an array index scheme."),
             "Shape and heap-order properties."),
            ("dsa-priority-queue", "Priority queue",
             "Use a priority queue as an ADT.",
             D("Contrast heap vs BST for priority retrieval."),
             "Java PriorityQueue; C++ priority_queue as equivalent."),
            ("dsa-heapify", "Heapify",
             "Build a heap and sift up/down.",
             D("Explain Floyd heapify at a high level."),
             "O(n) build vs repeated insert."),
            ("dsa-top-k", "Top-K",
             "Select top K with a heap.",
             D("Choose min-heap vs max-heap for top-K."),
             "Standard interview pattern."),
            ("dsa-heap-scheduling", "Scheduling patterns",
             "Use heaps for time/priority scheduling prompts.",
             D("Describe one scheduling pattern that needs a heap."),
             "Not OS scheduling theory."),
        ], jheap),
        ("dsa-graphs", "Graphs", [
            ("dsa-graph-representations", "Graph representations",
             "Build adjacency lists.",
             D("Represent an undirected graph in Java."),
             "Vertices, edges, directed vs undirected. Lists/maps of neighbors."),
            ("dsa-graph-bfs", "Graph BFS",
             "Traverse a graph with a queue.",
             D("Implement BFS without copying."),
             "Unweighted shortest path as a BFS consequence."),
            ("dsa-graph-dfs", "Graph DFS",
             "Traverse a graph with recursion or an explicit stack.",
             D("Implement DFS."),
             "Connected exploration."),
            ("dsa-connected-components", "Connected components",
             "Count or label components.",
             D("Explain BFS/DFS from unvisited nodes."),
             "Undirected connectivity."),
            ("dsa-graph-cycle", "Cycle detection",
             "Detect cycles in undirected and directed graphs at V1 depth.",
             D("Contrast parent-marked undirected cycles vs color-marked directed cycles."),
             "Needed before topological sort."),
            ("dsa-bipartite", "Bipartite graphs",
             "Check bipartiteness with two-coloring.",
             D("Two-color a small graph or show it is not bipartite."),
             "BFS/DFS coloring."),
        ], jgraph),
        ("dsa-topo", "Topological Sorting", [
            ("dsa-topological-sort", "Topological sorting",
             "Order a DAG.",
             D("Explain why cycles forbid topo sort."),
             "Kahn and/or DFS finishing times at V1 depth."),
        ], jgraph),
        ("dsa-union-find", "Union-Find", [
            ("dsa-union-find", "Union-Find",
             "Maintain disjoint sets.",
             D("Explain find and union."),
             "Connectivity. Path compression as explanation."),
        ], jgraph),
        ("dsa-shortest-paths", "Shortest Paths", [
            ("dsa-unweighted-shortest", "Unweighted shortest paths",
             "Use BFS for unweighted distances.",
             D("Contrast BFS distance vs Dijkstra."),
             "Already prepared by graph BFS."),
            ("dsa-dijkstra", "Dijkstra",
             "Explain Dijkstra for non-negative weights.",
             D("Trace Dijkstra on a tiny weighted graph."),
             "Priority-queue Dijkstra. Bellman-Ford named only."),
        ], jgraph + ["java-priority-queue"]),
        ("dsa-mst", "Minimum Spanning Trees", [
            ("dsa-mst", "MST",
             "Explain a minimum spanning tree and one construction idea.",
             D("Contrast Kruskal vs Prim at a high level."),
             "Interview/career value: concept plus one implementation sketch. Not a CP catalog."),
        ], jgraph),
        ("dsa-greedy", "Greedy Algorithms", [
            ("dsa-greedy-reasoning", "Greedy reasoning",
             "Identify when a local choice can work.",
             D("Give one greedy success and one greedy failure."),
             "Language-independent reasoning."),
            ("dsa-greedy-exchange", "Exchange / intuitive proof",
             "Justify a greedy choice at an intuitive exchange level.",
             D("Sketch why swapping to the greedy choice does not worsen a toy example."),
             "Not a formal proof course."),
            ("dsa-interval-problems", "Interval problems",
             "Solve interval selection/overlap style prompts.",
             D("Sort intervals and apply a greedy pass."),
             "A core interview family."),
            ("dsa-greedy-scheduling", "Scheduling",
             "Apply greedy scheduling patterns.",
             D("State the usual sort key for a classic scheduling greedy."),
             "Not OS schedulers."),
            ("dsa-greedy-patterns", "Classic greedy patterns",
             "Recognize Huffman/activity-selection style patterns at V1 depth.",
             D("Classify a prompt as greedy vs DP."),
             "Knowing when greedy is not enough."),
        ]),
        ("dsa-dp", "Dynamic Programming", [
            ("dsa-dp-mindset", "DP mindset",
             "Recognize overlapping subproblems and optimal substructure.",
             D("Write a recurrence for a toy problem."),
             "The idea before the tables."),
            ("dsa-memoization", "Memoization",
             "Cache recursive results.",
             D("Implement memoized recursion in Java."),
             "Top-down."),
            ("dsa-tabulation", "Tabulation",
             "Fill a table bottom-up.",
             D("Convert a memoized recurrence to a table."),
             "Bottom-up."),
            ("dsa-dp-state", "State definition",
             "Choose what a DP state means.",
             D("Name the indices/parameters of a state."),
             "Most DP bugs are bad states."),
            ("dsa-dp-transition", "Transition",
             "Write how a state is computed from others.",
             D("Write one transition equation."),
             "The recurrence in table form."),
            ("dsa-dp-1d", "1D DP",
             "Solve linear DP.",
             D("Implement a 1D DP in Java without copying."),
             "Climbing-stairs / house-robber family."),
            ("dsa-dp-2d", "2D DP",
             "Fill a table over two indices.",
             D("Dry-run a small 2D table."),
             "Grid and string DP at V1 depth."),
            ("dsa-subsequence-dp", "Subsequence DP",
             "Handle LCS/LIS-style subsequence states.",
             D("Define LCS state in one sentence."),
             "Common interview family."),
            ("dsa-knapsack", "Knapsack",
             "Use 0/1 knapsack as a template.",
             D("Write the 0/1 knapsack transition."),
             "Bounded knapsack variants named, not all coded."),
            ("dsa-grid-dp", "Grid DP",
             "DP on a grid.",
             D("Count paths or min-path on a small grid."),
             "Unique paths / min path sum family."),
            ("dsa-interval-dp", "Interval DP concepts",
             "Explain DP on intervals at a conceptual level.",
             D("State when a state is a subarray/interval."),
             "Concept for career value; not a full CP drill."),
            ("dsa-dp-optimization", "DP optimization",
             "Name space and time optimizations at V1 depth.",
             D("Reduce a 2-row DP to rolling arrays when valid."),
             "No exotic CHT/Knuth optimization as a mastery gate."),
        ]),
        ("dsa-advanced-patterns", "Advanced Problem-Solving Patterns", [
            ("dsa-tries", "Tries",
             "Explain a trie and when to use one.",
             D("Insert and search a word in a trie conceptually; implement in Java if mapped."),
             "Prefix problems. Justified for interviews."),
            ("dsa-bit-manipulation", "Bit manipulation",
             "Use AND/OR/XOR/shifts for interview-level bits.",
             D("Check a bit and count set bits."),
             "Not a CPU course. C++ and Java bit ops are equivalent enough."),
            ("dsa-segment-tree-concept", "Segment tree concept",
             "Explain what a segment tree stores.",
             D("State range-query vs Fenwick at a one-paragraph level."),
             "Concept only unless a later mapping justifies implementation."),
            ("dsa-advanced-graphs", "Advanced graph concepts",
             "Name SCC/bridges/articulation at recognition level.",
             D("State one situation that needs more than BFS/DFS/Dijkstra."),
             "Recognition, not a CP graph encyclopedia."),
            ("dsa-advanced-dp", "Advanced DP",
             "Recognize digit DP / DP on trees / bitmask DP by name.",
             D("State when bitmask DP applies (small n)."),
             "Career/interview recognition only. Not a mastery gate for every variant."),
            ("dsa-pattern-selection", "Pattern selection",
             "Choose among hash, two pointers, window, graph, DP, greedy.",
             D("Classify 5 unseen prompts into patterns on paper."),
             "Interview pattern recognition."),
            ("dsa-interview-hygiene", "Interview hygiene",
             "Narrate complexity, edges, Java vs C++ only if asked.",
             D("Present one solution with complexity and tests."),
             "How you talk through a problem. Primary language is Java."),
        ]),
    ]
